// AUTO-GENERATED by tools/runtime/generate-runtime.mjs. DO NOT EDIT.
import Foundation

public struct RuntimeActionDescriptor: Sendable, Equatable {
    public let action: String
    public let value: String?
    public let requiredPayload: [String]
    public let guards: [String]
    public let coreSequence: [String]
    public let hostRequest: String?
}

public enum GeneratedRuntimeActions {
    public static let schemaVersion = 2
    public static let byEvent: [String: RuntimeActionDescriptor] = [
        "route.push": RuntimeActionDescriptor(action: "pushRoute", value: nil, requiredPayload: ["routeId"], guards: ["loadingFalse"], coreSequence: [], hostRequest: nil),
        "route.replace": RuntimeActionDescriptor(action: "replaceRoute", value: nil, requiredPayload: ["routeId"], guards: ["loadingFalse"], coreSequence: [], hostRequest: nil),
        "route.pop": RuntimeActionDescriptor(action: "popRoute", value: nil, requiredPayload: [], guards: ["loadingFalse"], coreSequence: [], hostRequest: nil),
        "route.popToRoot": RuntimeActionDescriptor(action: "popToRoot", value: nil, requiredPayload: [], guards: ["loadingFalse"], coreSequence: [], hostRequest: nil),
        "mainTab.select": RuntimeActionDescriptor(action: "selectTab", value: nil, requiredPayload: ["tab"], guards: ["loadingFalse", "overlayEmpty"], coreSequence: [], hostRequest: nil),
        "overlay.dialog.open": RuntimeActionDescriptor(action: "setOverlay", value: "dialog", requiredPayload: [], guards: [], coreSequence: [], hostRequest: nil),
        "overlay.dialog.close": RuntimeActionDescriptor(action: "clearOverlay", value: nil, requiredPayload: [], guards: [], coreSequence: [], hostRequest: nil),
        "overlay.sheet.open": RuntimeActionDescriptor(action: "setOverlay", value: "sheet", requiredPayload: [], guards: [], coreSequence: [], hostRequest: nil),
        "overlay.sheet.close": RuntimeActionDescriptor(action: "clearOverlay", value: nil, requiredPayload: [], guards: [], coreSequence: [], hostRequest: nil),
        "overlay.keyboard.open": RuntimeActionDescriptor(action: "setOverlay", value: "keyboard", requiredPayload: [], guards: [], coreSequence: [], hostRequest: nil),
        "overlay.keyboard.close": RuntimeActionDescriptor(action: "clearOverlay", value: nil, requiredPayload: [], guards: [], coreSequence: [], hostRequest: nil),
        "reader.directory.open": RuntimeActionDescriptor(action: "setOverlay", value: "directory", requiredPayload: [], guards: [], coreSequence: [], hostRequest: nil),
        "reader.directory.close": RuntimeActionDescriptor(action: "clearOverlayIfMatches", value: "directory", requiredPayload: [], guards: [], coreSequence: [], hostRequest: nil),
        "reader.appearance.open": RuntimeActionDescriptor(action: "setOverlay", value: "appearance", requiredPayload: [], guards: [], coreSequence: [], hostRequest: nil),
        "reader.settings.open": RuntimeActionDescriptor(action: "setOverlay", value: "settings", requiredPayload: [], guards: [], coreSequence: [], hostRequest: nil),
        "reader.settings.close": RuntimeActionDescriptor(action: "clearOverlay", value: nil, requiredPayload: [], guards: [], coreSequence: [], hostRequest: nil),
        "reader.sourceSwitch.open": RuntimeActionDescriptor(action: "setOverlay", value: "source-switch", requiredPayload: [], guards: [], coreSequence: [], hostRequest: nil),
        "reader.sourceSwitch.close": RuntimeActionDescriptor(action: "clearOverlay", value: nil, requiredPayload: [], guards: [], coreSequence: [], hostRequest: nil),
        "book.open": RuntimeActionDescriptor(action: "bookOpenSequence", value: nil, requiredPayload: ["bookId", "sourceId", "sourceKind"], guards: [], coreSequence: ["source.detail", "chapter.list", "content.load", "reader.location.resolve"], hostRequest: nil),
        "reader.enter": RuntimeActionDescriptor(action: "pushRoute", value: "immersive-reading", requiredPayload: [], guards: ["loadingFalse"], coreSequence: [], hostRequest: nil),
        "reader.exit": RuntimeActionDescriptor(action: "popRoute", value: nil, requiredPayload: [], guards: [], coreSequence: [], hostRequest: nil),
        "reader.page.next": RuntimeActionDescriptor(action: "readerPageStep", value: "1", requiredPayload: [], guards: [], coreSequence: ["reader.location.resolve"], hostRequest: nil),
        "reader.page.prev": RuntimeActionDescriptor(action: "readerPageStep", value: "-1", requiredPayload: [], guards: [], coreSequence: ["reader.location.resolve"], hostRequest: nil),
        "reader.tts.start": RuntimeActionDescriptor(action: "startSession", value: "tts", requiredPayload: [], guards: [], coreSequence: ["tts.queue.start"], hostRequest: "tts.system.start"),
        "reader.tts.stop": RuntimeActionDescriptor(action: "stopSession", value: nil, requiredPayload: [], guards: [], coreSequence: ["tts.queue.stop"], hostRequest: "tts.system.stop"),
        "reader.autoPage.start": RuntimeActionDescriptor(action: "startSession", value: "auto-page", requiredPayload: [], guards: [], coreSequence: [], hostRequest: nil),
        "reader.autoPage.stop": RuntimeActionDescriptor(action: "stopSession", value: nil, requiredPayload: [], guards: [], coreSequence: [], hostRequest: nil),
        "reducedMotion.enable": RuntimeActionDescriptor(action: "setReducedMotion", value: "true", requiredPayload: [], guards: [], coreSequence: [], hostRequest: nil),
        "reducedMotion.disable": RuntimeActionDescriptor(action: "setReducedMotion", value: "false", requiredPayload: [], guards: [], coreSequence: [], hostRequest: nil),
        "source.switch.open": RuntimeActionDescriptor(action: "pushRoute", value: "source-switch", requiredPayload: [], guards: ["loadingFalse"], coreSequence: [], hostRequest: nil),
        "source.switch.cancel": RuntimeActionDescriptor(action: "popRoute", value: nil, requiredPayload: [], guards: [], coreSequence: [], hostRequest: nil),
        "sync.run": RuntimeActionDescriptor(action: "emitEffects", value: nil, requiredPayload: [], guards: [], coreSequence: ["sync.snapshot", "sync.push"], hostRequest: nil),
        "webdav.config.test": RuntimeActionDescriptor(action: "emitEffects", value: nil, requiredPayload: [], guards: [], coreSequence: ["sync.push"], hostRequest: "http.execute"),
        "import.start": RuntimeActionDescriptor(action: "emitEffects", value: nil, requiredPayload: [], guards: [], coreSequence: ["import.parse"], hostRequest: nil),
        "import.apply": RuntimeActionDescriptor(action: "emitEffects", value: nil, requiredPayload: [], guards: [], coreSequence: ["import.persist"], hostRequest: nil),
        "import.cancel": RuntimeActionDescriptor(action: "emitEffects", value: nil, requiredPayload: [], guards: [], coreSequence: ["import.rollback"], hostRequest: nil),
        "source.switch.confirm": RuntimeActionDescriptor(action: "emitEffects", value: nil, requiredPayload: [], guards: [], coreSequence: ["source.switch.commit"], hostRequest: nil),
        "source.switch.rollback": RuntimeActionDescriptor(action: "emitEffects", value: nil, requiredPayload: [], guards: [], coreSequence: ["source.switch.rollback"], hostRequest: nil),
        "reader.font.import": RuntimeActionDescriptor(action: "appearanceTransaction", value: "font.register", requiredPayload: [], guards: [], coreSequence: [], hostRequest: nil),
        "reader.font.delete": RuntimeActionDescriptor(action: "appearanceTransaction", value: "font.unregister", requiredPayload: [], guards: [], coreSequence: [], hostRequest: nil),
        "reader.theme.new": RuntimeActionDescriptor(action: "appearanceTransaction", value: "theme.create", requiredPayload: [], guards: [], coreSequence: [], hostRequest: nil),
        "reader.theme.edit": RuntimeActionDescriptor(action: "appearanceTransaction", value: "theme.update", requiredPayload: [], guards: [], coreSequence: [], hostRequest: nil),
        "reader.theme.delete": RuntimeActionDescriptor(action: "appearanceTransaction", value: "theme.delete", requiredPayload: [], guards: [], coreSequence: [], hostRequest: nil),
        "reader.typography.persist": RuntimeActionDescriptor(action: "appearanceTransaction", value: "typography.persist", requiredPayload: [], guards: [], coreSequence: [], hostRequest: nil),
        "reader.config.restart.simulate": RuntimeActionDescriptor(action: "appearanceTransaction", value: "config.loadPersisted", requiredPayload: [], guards: [], coreSequence: [], hostRequest: nil),
        "reader.config.persist": RuntimeActionDescriptor(action: "appearanceTransaction", value: "config.savePersisted", requiredPayload: [], guards: [], coreSequence: [], hostRequest: nil),
        "reader.replace.apply": RuntimeActionDescriptor(action: "emitEffects", value: nil, requiredPayload: [], guards: [], coreSequence: ["replace.apply"], hostRequest: nil),
        "reader.replace.create": RuntimeActionDescriptor(action: "emitEffects", value: nil, requiredPayload: [], guards: [], coreSequence: ["replace.persist"], hostRequest: nil),
        "reader.replace.validate": RuntimeActionDescriptor(action: "emitEffects", value: nil, requiredPayload: [], guards: [], coreSequence: ["replace.validate"], hostRequest: nil),
        "rss.refresh": RuntimeActionDescriptor(action: "emitEffects", value: nil, requiredPayload: [], guards: [], coreSequence: ["rss.feed.refresh"], hostRequest: nil),
        "rss.subscription.add": RuntimeActionDescriptor(action: "emitEffects", value: nil, requiredPayload: [], guards: [], coreSequence: ["rss.subscription.persist"], hostRequest: nil),
        "rss.subscription.delete": RuntimeActionDescriptor(action: "emitEffects", value: nil, requiredPayload: [], guards: [], coreSequence: ["rss.subscription.remove"], hostRequest: nil),
        "rss.subscription.edit": RuntimeActionDescriptor(action: "emitEffects", value: nil, requiredPayload: [], guards: [], coreSequence: ["rss.subscription.persist"], hostRequest: nil),
        "rss.entry.open": RuntimeActionDescriptor(action: "emitEffects", value: nil, requiredPayload: [], guards: [], coreSequence: ["rss.entry.read"], hostRequest: nil),
        "rss.favorite.add": RuntimeActionDescriptor(action: "emitEffects", value: nil, requiredPayload: [], guards: [], coreSequence: ["rss.favorite.persist"], hostRequest: nil),
        "rss.favorite.remove": RuntimeActionDescriptor(action: "emitEffects", value: nil, requiredPayload: [], guards: [], coreSequence: ["rss.favorite.remove"], hostRequest: nil),
        "sync.start": RuntimeActionDescriptor(action: "emitEffects", value: nil, requiredPayload: [], guards: [], coreSequence: ["sync.snapshot"], hostRequest: nil),
        "sync.progress": RuntimeActionDescriptor(action: "emitEffects", value: nil, requiredPayload: [], guards: [], coreSequence: ["sync.push"], hostRequest: nil),
        "sync.complete": RuntimeActionDescriptor(action: "emitEffects", value: nil, requiredPayload: [], guards: [], coreSequence: ["sync.push"], hostRequest: nil),
        "sync.conflict": RuntimeActionDescriptor(action: "emitEffects", value: nil, requiredPayload: [], guards: [], coreSequence: ["sync.conflict.detect"], hostRequest: nil),
        "sync.resolve": RuntimeActionDescriptor(action: "emitEffects", value: nil, requiredPayload: [], guards: [], coreSequence: ["sync.conflict.resolve"], hostRequest: nil)
    ]
}
