import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import vm from "node:vm";
const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const read = (file) => readFileSync(join(root, file), "utf8");
const rendererSource = read("renderers/d2-settings-sync-renderers.js"), declarationSource = read("control-identity-declarations.js"), runtimeSource = read("render-runtime.js"), kitSource = read("shared-shell-kit/kit.js"), appearanceSource = read("appearance-spec.js");
function fresh() { const window = { localStorage: { getItem() { return null; }, setItem() {}, removeItem() {} }, ReaderFrontendDemoDraftRouteContract: { routes: {}, routePresentation: {} } }; const context = vm.createContext({ window, module: { exports: {} }, Promise, setTimeout }); [kitSource, appearanceSource, declarationSource, rendererSource].forEach((source) => new vm.Script(source).runInContext(context)); const api = window.ReaderD2SettingsSyncRenderers; api.restore.initState(); return api; }
function values(html, attr) { return [...html.matchAll(new RegExp(`${attr}="([^"]+)"`, "g"))].map((match) => match[1]); }

test("R2a restore-preview declares exactly 47 mapped semantic controls", () => { const box = { module: { exports: {} }, window: {} }; new vm.Script(declarationSource).runInNewContext(box); const rows = box.module.exports.CANONICAL_CONTROL_DECLARATIONS.filter((entry) => entry.source === "restore-preview-action"); assert.equal(rows.length, 47); assert.equal(new Set(rows.map((entry) => entry.controlKey)).size, 47); assert.ok(rows.every((entry) => entry.mappingStatus === "mapped" && entry.instanceKey === null && !/\.n\d+|selector|ordinal/.test(entry.settingsKey))); });
test("R2a seven canonical routes stamp all 47 controls with five attrs", () => { const api = fresh(); const expected = { "restore-confirm": 11, "restore-scopes": 13, "restore-preview": 3, "restore-progress": 3, "restore-running": 3, "restore-conflict": 11, "restore-result": 3 }; let total = 0; for (const [route, count] of Object.entries(expected)) { const html = api.renderD2Route(route, {}, {}); total += count; for (const attr of ["data-entity-key", "data-control-key", "data-control-id", "data-ui-event", "data-settings-key"]) assert.equal(values(html, attr).length, count, `${route} ${attr}`); } assert.equal(total, 47); });
test("R2a renderer specs and generated declarations have zero mismatch", () => { const api = fresh(); const box = { module: { exports: {} }, window: {} }; new vm.Script(declarationSource).runInNewContext(box); const left = box.module.exports.CANONICAL_CONTROL_DECLARATIONS.filter((entry) => entry.source === "restore-preview-action").map((entry) => `${entry.route}|${entry.state}|${entry.settingsKey}`).sort(); const right = api.RESTORE_CONTROL_SPECS.map((entry) => `${entry.route}|${entry.state}|${entry.settingsKey}`).sort(); assert.equal(JSON.stringify(left), JSON.stringify(right)); });
test("R3a failed and partial route drift is frozen into result outcome", () => { const api = fresh(); assert.equal(api.renderD2Route("restore-failed", {}, {}), ""); assert.equal(api.renderD2Route("restore-partial", {}, {}), ""); assert.match(runtimeSource, /legacy restore route is fail-loud/); });
test("R3a all canonical legacy fallbacks are fail-loud", () => assert.match(runtimeSource, /restoreFlowV2 \(d2-settings-sync-renderers\.js\)/));
test("R3a Phone and Tablet reuse the same control keys", () => { const api = fresh(); for (const route of ["restore-confirm", "restore-scopes", "restore-conflict"]) { const html = api.renderD2Route(route, {}, {}); const keys = values(html, "data-control-key").sort(); assert.deepEqual(values(`<main data-viewport="phone">${html}</main>`, "data-control-key").sort(), keys); assert.deepEqual(values(`<main data-viewport="tablet">${html}</main>`, "data-control-key").sort(), keys); } });
test("R3a landscape aliases Tablet and Compact/Fold are prohibited", () => assert.doesNotMatch(rendererSource, /compact-landscape|foldable|data-viewport="compact"|data-viewport="fold"/i));
test("R3a restore rendering is byte-stable without dispatch", () => { const api = fresh(); assert.equal(api.renderD2Route("restore-preview", {}, {}), api.renderD2Route("restore-preview", {}, {})); });
