import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import vm from "node:vm";
const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const sources = ["shared-shell-kit/kit.js", "appearance-spec.js", "control-identity-declarations.js", "renderers/d2-settings-sync-renderers.js"].map((file) => readFileSync(join(root, file), "utf8"));
function fresh() { const window = { localStorage: { getItem() { return null; }, setItem() {}, removeItem() {} }, ReaderFrontendDemoDraftRouteContract: { routes: {}, routePresentation: {} } }; const context = vm.createContext({ window, module: { exports: {} }, Promise, setTimeout }); sources.forEach((source) => new vm.Script(source).runInContext(context)); const api = window.ReaderD2SettingsSyncRenderers; api.restore.initState(); return api; }

test("R2b state owner contains scope mode conflict progress and outcome", () => { const state = fresh().restore.getState(); for (const key of ["mode", "selectedScopes", "conflictChoices", "phase", "outcome", "progress", "pending", "requestEpoch"]) assert.ok(Object.prototype.hasOwnProperty.call(state, key)); });
test("R2b scope toggles never allow an empty restore selection", () => { const api = fresh(); for (const scope of ["bookshelf", "progress", "settings", "sources"]) api.restore.dispatch({ type: "TOGGLE_SCOPE", scope }); assert.equal(api.restore.getState().selectedScopes.length, 1); });
test("R2b restore mode accepts full/partial only", () => { const api = fresh(); api.restore.dispatch({ type: "SELECT_MODE", mode: "partial" }); api.restore.dispatch({ type: "SELECT_MODE", mode: "invalid" }); assert.equal(api.restore.getState().mode, "partial"); });
test("R2b conflict choice supports individual and batch resolution", () => { const api = fresh(); api.restore.dispatch({ type: "CHOOSE_CONFLICT", conflictId: "group", choice: "local" }); assert.equal(api.restore.getState().conflictChoices.group, "local"); api.restore.dispatch({ type: "CHOOSE_ALL", choice: "remote" }); assert.ok(Object.values(api.restore.getState().conflictChoices).every((choice) => choice === "remote")); });
test("R2b preview commit confirm opens and closes inside one owner", () => { const api = fresh(); api.restore.dispatch({ type: "COMMIT_CONFIRM_OPEN" }); assert.equal(api.restore.getState().confirmOpen, true); assert.match(api.renderD2Route("restore-preview", {}, {}), /role="dialog"/); api.restore.dispatch({ type: "COMMIT_CONFIRM_CLOSE" }); assert.equal(api.restore.getState().confirmOpen, false); });
test("R2b progress is clamped to 0..100", () => { const api = fresh(); api.restore.dispatch({ type: "RESTORE_PROGRESS", progress: 150 }); assert.equal(api.restore.getState().progress, 100); api.restore.dispatch({ type: "RESTORE_PROGRESS", progress: -10 }); assert.equal(api.restore.getState().progress, 0); });
test("R2b async restore commits success partial and failed outcomes", async () => { const api = fresh(); assert.equal((await api.restore.execute(() => ({ outcome: "success" }))).status, "success"); assert.equal(api.restore.getState().outcome, "success"); api.restore.initState(); assert.equal((await api.restore.execute(() => ({ outcome: "partial" }))).status, "partial"); assert.equal(api.restore.getState().outcome, "partial"); api.restore.initState(); assert.equal((await api.restore.execute(() => { throw new Error("hash mismatch"); })).status, "failed"); assert.equal(api.restore.getState().outcome, "failed"); });
test("R2b duplicate execution is rejected", async () => { const api = fresh(); let release; const pending = api.restore.execute(() => new Promise((resolve) => { release = resolve; })); await Promise.resolve(); assert.equal((await api.restore.execute(() => true)).status, "duplicate"); release({ outcome: "success" }); assert.equal((await pending).status, "success"); });
test("R2b cancel invalidates in-flight completion as stale", async () => { const api = fresh(); let release; const pending = api.restore.execute(() => new Promise((resolve) => { release = resolve; })); await Promise.resolve(); assert.equal(api.restore.cancel().status, "cancelled"); release({ outcome: "success" }); assert.equal((await pending).status, "stale"); assert.equal(api.restore.getState().phase, "cancelled"); });
test("R2b failed and partial visuals render through restore-result only", async () => { const api = fresh(); await api.restore.execute(() => ({ outcome: "partial" })); assert.match(api.renderD2Route("restore-result", {}, {}), /恢复部分完成/); api.restore.initState(); await api.restore.execute(() => { throw new Error("bad backup"); }); assert.match(api.renderD2Route("restore-result", {}, {}), /恢复失败/); });
