import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import vm from "node:vm";
const root=join(dirname(fileURLToPath(import.meta.url)),"..");
const source=readFileSync(join(root,"renderers/w3-source-switch-renderers.js"),"utf8");
const responsive=readFileSync(join(root,"styles/06-responsive.css"),"utf8");
const adaptive=readFileSync(join(root,"styles/05-flow-adaptive.css"),"utf8");
const ids=["source-youshu","source-biquge-mirror","source-light-novel","source-cloud-library","source-aggregate-1","source-aggregate-2","source-backup-a","source-backup-b","source-chapter-sync","source-local-cache","source-old-backup"];
const fixture={reader:{title:"长夜余火"},flow:{chapter:"第 32 章 雨夜",candidates:ids.map((sourceId,index)=>({sourceId,source:sourceId,state:index===0?"当前":index===10?"落后":"可切换",speed:"120 ms",chapter:"第 32 章"}))}};
function fresh(){const window={setTimeout,ReaderShellKit:{icon:()=>"",renderFlowShell:(o)=>`${o.stepHtml}${o.comparisonHtml}`}};const ctx=vm.createContext({window,globalThis:window,module:{exports:{}},setTimeout,Promise,Map,Set});new vm.Script(source).runInContext(ctx);window.ReaderW3SourceSwitchRenderers.sourceSwitch.reset();return window.ReaderW3SourceSwitchRenderers;}
test("R3a candidate window is a labelled modal dialog",()=>assert.match(fresh().sourceSwitchV2(fixture,"source-switch",{}),/role="dialog" aria-modal="true" aria-labelledby="source-switch-title"/));
test("R3a candidate collection uses listbox/option semantics",()=>{const h=fresh().sourceSwitchV2(fixture,"source-switch",{});assert.match(h,/role="listbox"/);assert.equal((h.match(/role="option"/g)||[]).length,11);});
test("R3a candidate window has no confirmation footer because rows switch directly",()=>{const h=fresh().sourceSwitchV2(fixture,"source-switch",{});assert.match(h,/点击可用书源立即切换/);assert.doesNotMatch(h,/data-source-switch-action="confirm"|fd-source-switch-result|检查并确认|>继续</);});
test("R3a current and unavailable sources are disabled",()=>{const h=fresh().sourceSwitchV2(fixture,"source-switch",{});assert.match(h,/data-source-id="source-youshu"[^>]+aria-disabled="true"[^>]+disabled/);assert.match(h,/data-source-id="source-old-backup"[^>]+aria-disabled="true"[^>]+disabled/);});
test("R3a selected source exposes aria-selected",()=>{const a=fresh();a.sourceSwitch.dispatch({type:"SELECT",sourceId:"source-biquge-mirror"});assert.match(a.sourceSwitchV2(fixture,"source-switch",{}),/data-source-id="source-biquge-mirror"[^>]+aria-selected="true"/);});
test("R3a close control carries exact focus-return marker",()=>{const a=fresh();a.sourceSwitch.dispatch({type:"OPEN",navigationOriginRoute:"book-detail",visualContextRoute:"reader",originControlKey:"exact-origin-key"});assert.match(a.sourceSwitchV2(fixture,"source-switch",{}),/data-restore-focus="exact-origin-key"/);});
test("R3a loading exposes status, live region and busy state",()=>{const h=fresh().sourceSwitchV2(fixture,"source-switch-loading",{});assert.match(h,/role="status" aria-live="polite" aria-busy="true"/);assert.match(h,/data-settings-key="cancel"/);});
test("R3a error exposes alert semantics",()=>assert.match(fresh().sourceSwitchV2(fixture,"source-switch-error",{}),/role="alert"/));
test("R3a rollback is modal and safe cancel has initial focus",()=>{const h=fresh().sourceSwitchV2(fixture,"source-switch-rollback",{});assert.match(h,/role="dialog" aria-modal="true"/);assert.match(h,/data-dialog-initial-focus="rollback-cancel"/);});
test("R3a candidate and close interaction hosts are at least 44px",()=>{assert.match(responsive,/fd-source-candidate-row[\s\S]{0,180}min-height:\s*44px/);assert.match(responsive,/fd-source-window-close[\s\S]{0,120}width:\s*44px;[\s\S]{0,50}height:\s*44px/);assert.match(adaptive,/fd-source-window-close[\s\S]{0,160}width:\s*44px;[\s\S]{0,50}height:\s*44px/);});
test("R3a trailing latency and chapter columns remain right-side columns",()=>assert.match(responsive,/grid-template-columns:\s*minmax\(82px, 1fr\) 45px minmax\(86px, 1\.08fr\)/));
test("R3a route-local control keys are unique",()=>{const a=fresh();for(const route of a.ROUTES){const keys=[...a.sourceSwitchV2(fixture,route,{}).matchAll(/data-control-key="([^"]+)"/g)].map(m=>m[1]);assert.equal(new Set(keys).size,keys.length,route);}});
