import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import vm from "node:vm";
const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const sources = ["shared-shell-kit/kit.js", "appearance-spec.js", "control-identity-declarations.js", "renderers/d2-settings-sync-renderers.js"].map((file) => readFileSync(join(root, file), "utf8"));
function fresh() { const window = { localStorage: { getItem() { return null; }, setItem() {}, removeItem() {} }, ReaderFrontendDemoDraftRouteContract: { routes: {}, routePresentation: {} } }; const context = vm.createContext({ window, module: { exports: {} }, Promise, setTimeout }); sources.forEach((source) => new vm.Script(source).runInContext(context)); const api = window.ReaderD2SettingsSyncRenderers; api.restore.initState(); return api; }

test("R3a scope choices expose pressed state and stable control identities", () => { const html = fresh().renderD2Route("restore-confirm", {}, {}); assert.match(html, /data-restore-scope="bookshelf" aria-pressed="true"[^>]*data-control-key=/); assert.match(html, /role="switch" aria-checked="true"[^>]*data-settings-key="scope-bookshelf-switch"/); });
test("R3a restore modes are native keyboard-reachable buttons", () => { const html = fresh().renderD2Route("restore-scopes", {}, {}); assert.match(html, /data-d2-restore-mode="full"[^>]*data-settings-key="mode-full"/); assert.match(html, /data-d2-restore-mode="partial"[^>]*data-settings-key="mode-partial"/); });
test("R3a conflict pairs expose six separately identifiable native controls", () => { const html = fresh().renderD2Route("restore-conflict", {}, {}); for (const key of ["conflict-group-local", "conflict-group-remote", "conflict-progress-local", "conflict-progress-remote", "conflict-settings-local", "conflict-settings-remote"]) assert.match(html, new RegExp(`data-settings-key="${key}"`)); });
test("R3a commit dialog is modal labelled and has deterministic focus", () => { const api = fresh(); api.restore.dispatch({ type: "COMMIT_CONFIRM_OPEN" }); const html = api.renderD2Route("restore-preview", {}, {}); assert.match(html, /role="dialog" aria-modal="true" aria-labelledby="restore-commit-dialog-title"/); assert.match(html, /data-dialog-initial-focus="preview-previous"/); assert.match(html, /data-restore-focus="restore-commit"/); });
test("R3a active restore disables result action and reports busy", async () => { const api = fresh(); let release; const pending = api.restore.execute(() => new Promise((resolve) => { release = resolve; })); await Promise.resolve(); const progress = api.renderD2Route("restore-progress", {}, {}); const running = api.renderD2Route("restore-running", {}, {}); assert.match(progress, /data-settings-key="progress-result" aria-busy="true" disabled/); assert.match(running, /data-settings-key="running-result" aria-busy="true" disabled/); assert.match(running, /data-settings-key="restore-cancel"/); release({ outcome: "success" }); await pending; });
test("R3a failed outcome is an alert and exposes invalid state", async () => { const api = fresh(); await api.restore.execute(() => { throw new Error("ManifestHashMismatch"); }); const html = api.renderD2Route("restore-result", {}, {}); assert.match(html, /role="alert" aria-invalid="true"/); assert.match(html, /role="alert">ManifestHashMismatch/); });
test("R3a partial outcome remains a result state with accessible actions", async () => { const api = fresh(); await api.restore.execute(() => ({ outcome: "partial" })); const html = api.renderD2Route("restore-result", {}, {}); assert.match(html, /恢复部分完成/); assert.match(html, /data-settings-key="result-log"/); assert.match(html, /data-settings-key="result-bookshelf"/); });
test("R3a every stamped control has a non-empty accessible label source", () => { const api = fresh(); for (const route of ["restore-confirm", "restore-scopes", "restore-preview", "restore-progress", "restore-running", "restore-conflict", "restore-result"]) { const html = api.renderD2Route(route, {}, {}); for (const tag of html.match(/<(?:button|span)[^>]*data-control-key=[^>]*>/g) || []) assert.match(tag, /aria-label=|data-settings-key=/, `${route}: ${tag}`); } });
