import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import vm from "node:vm";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const sources = ["shared-shell-kit/kit.js", "appearance-spec.js", "control-identity-declarations.js", "renderers/d2-settings-sync-renderers.js"].map((file) => readFileSync(join(root, file), "utf8"));
function fresh() { const window = { localStorage: { getItem() { return null; }, setItem() {}, removeItem() {} }, ReaderFrontendDemoDraftRouteContract: { routes: {}, routePresentation: {} } }; const context = vm.createContext({ window, module: { exports: {} }, Promise, setTimeout }); sources.forEach((source) => new vm.Script(source).runInContext(context)); const api = window.ReaderD2SettingsSyncRenderers; api.syncBackup.initState(); return api; }

test("R3a switches expose role and checked state", () => { const html = fresh().renderD2Route("backup-settings", {}, {}); assert.match(html, /role="switch" aria-checked="true"/); assert.match(html, /role="switch" aria-checked="false"/); });
test("R3a selects expose listbox intent and keyboard focus", () => { const html = fresh().renderD2Route("backup-settings", {}, {}); assert.match(html, /aria-haspopup="listbox" aria-expanded="false"[^>]*role="button" tabindex="0"/); });
test("R3a restore cards and remote rows are keyboard reachable", () => { const api = fresh(); assert.match(api.renderD2Route("sync-backup", {}, {}), /fd-settings-backup-card[^>]*role="button" tabindex="0"/); assert.match(api.renderD2Route("remote-webdav-books", {}, {}), /data-settings-key="remote-long-night"[^>]*role="button" tabindex="0"|role="button" tabindex="0"[^>]*data-settings-key="remote-long-night"/); });
test("R3a overlay triggers carry focus-return markers", () => { const api = fresh(); assert.match(api.renderD2Route("backup-settings", {}, {}), /data-restore-focus="manual-backup-open"/); assert.match(api.renderD2Route("remote-webdav-books", {}, {}), /data-restore-focus="remote-cleanup"/); });
test("R3a manual dialog has modal semantics, label, and initial focus", () => { const api = fresh(); api.syncBackup.dispatch({ type: "MANUAL_BACKUP_OPEN" }); const html = api.renderD2Route("backup-settings", {}, {}); assert.match(html, /role="dialog" aria-modal="true" aria-labelledby="sync-backup-dialog-title"/); assert.match(html, /data-dialog-initial-focus="manual-backup-cancel"/); });
test("R3a loading connection disables the trigger and reports busy", async () => { const api = fresh(); let release; const pending = api.syncBackup.executeConnectionTest(() => new Promise((resolve) => { release = resolve; })); await Promise.resolve(); const html = api.renderD2Route("sync-backup", {}, {}); assert.match(html, /data-settings-key="test-connection"[^>]*aria-busy="true" disabled/); release(true); await pending; });
test("R3a sync loading disables the run button and exposes cancellation", async () => { const api = fresh(); let release; const pending = api.syncBackup.executeSync(() => new Promise((resolve) => { release = resolve; })); await Promise.resolve(); const html = api.renderD2Route("progress-sync", {}, {}); assert.match(html, /data-settings-key="sync-now"[^>]*aria-busy="true" disabled/); assert.match(html, /data-settings-key="sync-cancel"/); release(true); await pending; });
test("R3a failed async state is announced as invalid with error title", async () => { const api = fresh(); await api.syncBackup.executeConnectionTest(() => { throw new Error("401"); }); const html = api.renderD2Route("sync-backup", {}, {}); assert.match(html, /data-settings-key="test-connection"[^>]*aria-invalid="true"[^>]*title="401"/); });
test("R3a manual dialog disappears after cancel and focus marker remains", () => { const api = fresh(); api.syncBackup.dispatch({ type: "MANUAL_BACKUP_OPEN" }); api.syncBackup.dispatch({ type: "MANUAL_BACKUP_CANCEL" }); const html = api.renderD2Route("backup-settings", {}, {}); assert.doesNotMatch(html, /role="dialog"/); assert.match(html, /data-restore-focus="manual-backup-open"/); });
