#!/usr/bin/env node
// Reader UI Contract Codegen
// 从 contracts/*.schema.json + fixtures 生成 Swift / Kotlin / ArkTS 类型
// 输入只来自 contracts/，输出落到 generated/{swift,kotlin,arkts}，可重复生成。

import { readFileSync, writeFileSync, readdirSync, mkdirSync, existsSync } from "node:fs";
import { dirname, join, basename, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const REPO_ROOT = resolve(__dirname, "..", "..");
const CONTRACTS_DIR = join(REPO_ROOT, "contracts");
const GENERATED_DIR = join(REPO_ROOT, "generated");

// --- 工具函数 ---
function readJson(p) {
  return JSON.parse(readFileSync(p, "utf8"));
}

function toPascalCase(s) {
  // 把 kebab-case / snake_case / dotted.name 转为 PascalCase
  return s
    .replace(/[-_.]+/g, " ")
    .replace(/\s+(.)/g, (_, c) => c.toUpperCase())
    .replace(/^(.)/, (_, c) => c.toUpperCase())
    .replace(/\s+/g, "");
}

function toCamelCase(s) {
  const p = toPascalCase(s);
  return p.charAt(0).toLowerCase() + p.slice(1);
}

function stringLiteral(value) {
  return JSON.stringify(String(value));
}

function swiftMotionIdCase(id) {
  return id.replace(/[^A-Za-z0-9_]/g, "_");
}

function swiftEasingCase(easing) {
  return easing === "none" ? "noneValue" : easing.replace(/-/g, "_");
}

function kotlinCase(value) {
  return toPascalCase(String(value)).replace(/[^A-Za-z0-9_]/g, "_");
}

function reducedMotionInfo(item) {
  const guardRules = Array.isArray(item.guardRules) ? item.guardRules : [];
  const sourceRule = guardRules.find((rule) => String(rule).startsWith("reducedMotion:")) || null;
  return {
    forceZeroDuration: sourceRule === "reducedMotion:forceZeroDuration" || item.durationMs === 0,
    directManipulation: guardRules.some((rule) =>
      String(rule).startsWith("dragMustFollowFinger:") || String(rule).startsWith("releaseToSnap:")
    ),
    sourceRule,
  };
}

function swiftStringArray(values) {
  return `[${values.map(stringLiteral).join(", ")}]`;
}

function kotlinStringList(values) {
  return values.length > 0 ? `listOf(${values.map(stringLiteral).join(", ")})` : "emptyList()";
}

function arkTsStringArray(values) {
  return `[${values.map(stringLiteral).join(", ")}]`;
}

// --- 加载 schema 与 fixtures ---
function loadSchema(name) {
  return readJson(join(CONTRACTS_DIR, `${name}.schema.json`));
}

function loadFixtures(name) {
  const p = join(CONTRACTS_DIR, "fixtures", `${name}.fixtures.json`);
  if (!existsSync(p)) return [];
  return readJson(p);
}

// 提取 enum 值（schema 中 properties.<key>.enum）。无 enum 时返回 undefined 便于 fallback。
function extractEnum(schema, key) {
  const node = key.split(".").reduce((acc, k) => (acc ? acc[k] : undefined), schema.properties);
  if (!node) return undefined;
  if (Array.isArray(node.enum)) {
    const filtered = node.enum.filter((v) => v !== null);
    return filtered.length > 0 ? filtered : undefined;
  }
  return undefined;
}

// --- 生成 Swift ---
function genSwiftRoute(schema, fixtures) {
  const ids = extractEnum(schema, "id");
  const shells = extractEnum(schema, "shell");
  const mainTabs = ["bookshelf", "discover", "rss", "settings"];
  return `// AUTO-GENERATED by tools/codegen/generate.mjs. DO NOT EDIT.
// Source: contracts/route.schema.json + fixtures/route.fixtures.json
import Foundation

public enum RouteId: String, Codable, CaseIterable, Sendable {
${ids.map((id) => `    case ${toCamelCase(id).replace(/[^A-Za-z0-9_]/g, "_")} = "${id}"`).join("\n")}
}

public enum RouteShell: String, Codable, CaseIterable, Sendable {
${shells.map((s) => `    case ${toCamelCase(s)} = "${s}"`).join("\n")}
}

public enum MainTab: String, Codable, CaseIterable, Sendable {
${mainTabs.map((t) => `    case ${t}`).join("\n")}
}

public struct Route: Codable, Equatable, Sendable {
    public let id: RouteId
    public let shell: RouteShell
    public var params: [String: String]?
    public var mainTab: MainTab?
    public var deprecated: Bool?
    public var replacedBy: String?

    public init(id: RouteId, shell: RouteShell, params: [String: String]? = nil, mainTab: MainTab? = nil) {
        self.id = id
        self.shell = shell
        self.params = params
        self.mainTab = mainTab
    }
}
`;
}

function genSwiftUiEvent(schema, fixtures) {
  const types = extractEnum(schema, "type");
  return `// AUTO-GENERATED by tools/codegen/generate.mjs. DO NOT EDIT.
// Source: contracts/ui-event.schema.json + fixtures/ui-event.fixtures.json
import Foundation

public enum UiEventType: String, Codable, CaseIterable, Sendable {
${types.map((t) => `    case ${t.replace(/\./g, "_")} = "${t}"`).join("\n")}
}

public struct UiEvent: Codable, Equatable, Sendable {
    public let type: UiEventType
    public var payload: [String: AnyCodable]
    public var timestamp: Date?
    public var correlationId: String?

    public init(type: UiEventType, payload: [String: AnyCodable] = [:], correlationId: String? = nil) {
        self.type = type
        self.payload = payload
        self.correlationId = correlationId
    }
}

public struct AnyCodable: Codable, Equatable, Sendable {
    public let value: any Sendable
    public init(_ value: any Sendable) { self.value = value }
    public init(from decoder: Decoder) throws {
        let c = try decoder.singleValueContainer()
        if let v = try? c.decode(Bool.self) { self.value = v }
        else if let v = try? c.decode(Int.self) { self.value = v }
        else if let v = try? c.decode(Double.self) { self.value = v }
        else if let v = try? c.decode(String.self) { self.value = v }
        else if let v = try? c.decode([AnyCodable].self) { self.value = v }
        else if let v = try? c.decode([String: AnyCodable].self) { self.value = v }
        else { self.value = Optional<String>.none as String? }
    }
    public func encode(to encoder: Encoder) throws {
        var c = encoder.singleValueContainer()
        switch value {
        case let v as Bool: try c.encode(v)
        case let v as Int: try c.encode(v)
        case let v as Double: try c.encode(v)
        case let v as String: try c.encode(v)
        case let v as [AnyCodable]: try c.encode(v)
        case let v as [String: AnyCodable]: try c.encode(v)
        default: try c.encodeNil()
        }
    }
    public static func == (l: AnyCodable, r: AnyCodable) -> Bool {
        return String(describing: l.value) == String(describing: r.value)
    }
}
`;
}

function genSwiftUiState(schema) {
  return `// AUTO-GENERATED by tools/codegen/generate.mjs. DO NOT EDIT.
// Source: contracts/ui-state.schema.json
import Foundation

public enum ReaderMode: String, Codable, CaseIterable, Sendable {
    case defaultMode = "default"
    case loading
    case empty
    case error
    case offline
    case permission
}

public enum Overlay: String, Codable, CaseIterable, Sendable {
    case settings
    case readerControl = "reader-control"
    case directory
    case tts
    case appearance
    case autoPage = "auto-page"
    case contentSearch = "content-search"
    case contentReplacement = "content-replacement"
    case sourceSwitch = "source-switch"
    case bookAction = "book-action"
    case sortFilter = "sort-filter"
    case groupManagement = "group-management"
    case localImport = "local-import"
    case batchManagement = "batch-management"
    case readerNightState = "reader-night-state"
    case readerDebugInfo = "reader-debug-info"
    case readerBookCache = "reader-book-cache"
    case keyboard
    case dialog
    case sheet
    case toast
}

public enum ActiveSession: String, Codable, CaseIterable, Sendable {
    case reading
    case tts
    case autoPage = "auto-page"
}

public enum PageState: String, Codable, CaseIterable, Sendable {
    case defaultValue = "default"
    case loading
    case empty
    case error
    case offline
    case permission
    case coverMode = "cover-mode"
    case listMode = "list-mode"
    case shelfEmpty = "shelf-empty"
    case noCover = "no-cover"
    case longTitle = "long-title"
    case switchingSourceType = "switching-source-type"
    case sourceEmpty = "source-empty"
    case sourceUnavailable = "source-unavailable"
    case networkFailed = "network-failed"
    case refreshing
    case noSubscription = "no-subscription"
    case noUnread = "no-unread"
    case localDataLoading = "local-data-loading"
    case noBackup = "no-backup"
    case permissionMissing = "permission-missing"
    case topbarAction = "topbar-action"
}

public struct UiError: Codable, Equatable, Sendable {
    public let code: String
    public let message: String
    public var retryable: Bool?
}

public struct RouteRef: Codable, Equatable, Sendable {
    public let id: String
    public var params: [String: String]?
    public var stack: [RouteRef]?
}

public struct BookshelfUiState: Codable, Equatable, Sendable {
    public var viewMode: String?
    public var selectedGroupId: String?
    public var sortKey: String?
    public var sortOrder: String?
    public var filterKeys: [String]?
}

public struct DiscoverUiState: Codable, Equatable, Sendable {
    public var filter: String?
    public var sort: String?
    public var sortOpen: Bool?
    public var sourceType: String?
    public var sourceEnabled: [String: Bool]?
}

public struct ReaderUiState: Codable, Equatable, Sendable {
    public var turnDirection: String?
    public var pageIndex: Int?
    public var chapterIndex: Int?
    public var chapterProgress: Double?
    public var chapterDownloads: [String: String]?
    public var tts: [String: AnyCodable]?
    public var settings: [String: AnyCodable]?
    public var typography: [String: AnyCodable]?
    public var textSelectionOpen: Bool?
    public var selectedText: String?
    public var sessionCapsuleSnapshot: [String: AnyCodable]?
    public var controlSpaceSnapshot: [String: AnyCodable]?
    public var autoPageCountdown: Double?
    public var dockOffsets: [String: Double]?
    public var entryMotion: String?
}

public struct SettingsUiState: Codable, Equatable, Sendable {
    public var overlay: String?
    public var expandedOption: String?
    public var restoreAvailableScopes: [String]?
    public var restoreSelectedScopes: [String]?
}

public struct MotionUiState: Codable, Equatable, Sendable {
    public var overlaySequence: String?
    public var overlayRole: String?
    public var overlayAction: String?
    public var overlayFocusReturn: String?
    public var overlayReturnTarget: String?
    public var viewportOrientationMotion: String?
    public var viewportOrientationSequence: String?
    public var viewportOrientationTimer: Double?
    public var interruptMotion: String?
    public var interruptSequence: String?
    public var interruptTimer: Double?
    public var dropdownMotion: String?
    public var dropdownSwitchMotion: String?
    public var dropdownSwitchSequence: String?
    public var dropdownSwitchTimer: Double?
    public var segmentMotion: String?
    public var asyncRouteRequest: String?
    public var asyncResultMotion: String?
    public var asyncResultSequence: String?
}

public struct FirstOpenUiState: Codable, Equatable, Sendable {
    public var hasPlayed: Bool?
    public var motionTimer: Double?
}

public struct UiState: Codable, Equatable, Sendable {
    public var route: RouteRef
    public var tab: MainTab
    public var readerMode: ReaderMode
    public var overlay: Overlay?
    public var activeSession: ActiveSession?
    public var focusTarget: String?
    public var loading: Bool
    public var error: UiError?
    public var reducedMotion: Bool
    public var pageState: PageState?
    public var bookshelf: BookshelfUiState?
    public var discover: DiscoverUiState?
    public var reader: ReaderUiState?
    public var settings: SettingsUiState?
    public var motion: MotionUiState?
    public var firstOpen: FirstOpenUiState?

    public init(
        route: RouteRef,
        tab: MainTab,
        readerMode: ReaderMode,
        overlay: Overlay? = nil,
        activeSession: ActiveSession? = nil,
        focusTarget: String? = nil,
        loading: Bool,
        error: UiError? = nil,
        reducedMotion: Bool = false
    ) {
        self.route = route
        self.tab = tab
        self.readerMode = readerMode
        self.overlay = overlay
        self.activeSession = activeSession
        self.focusTarget = focusTarget
        self.loading = loading
        self.error = error
        self.reducedMotion = reducedMotion
    }
}
`;
}

function genSwiftViewState(schema) {
  const types = extractEnum(schema, "components.items.$defs.Component.properties.type") ||
    schema.$defs.Component.properties.type.enum || [];
  return `// AUTO-GENERATED by tools/codegen/generate.mjs. DO NOT EDIT.
// Source: contracts/view-state.schema.json
import Foundation

public enum ComponentType: String, Codable, CaseIterable, Sendable {
${types.map((t) => `    case ${toCamelCase(t)} = "${t}"`).join("\n")}
}

public struct ViewStateComponent: Codable, Equatable, Sendable {
    public let type: ComponentType
    public var id: String?
    public var props: [String: AnyCodable]?
    public var children: [ViewStateComponent]?
}

public struct ViewState: Codable, Equatable, Sendable {
    public let routeId: String
    public let pageState: PageState
    public var context: [String: AnyCodable]?
    public let components: [ViewStateComponent]
}
`;
}

function genSwiftMotion(schema, fixtures) {
  const ids = extractEnum(schema, "id");
  const easings = extractEnum(schema, "easing");
  const registry = fixtures.map((item) => {
    const guardRules = Array.isArray(item.guardRules) ? item.guardRules : [];
    const reduced = reducedMotionInfo(item);
    const durationToken = item.tokens?.durationToken ? stringLiteral(item.tokens.durationToken) : "nil";
    const easingToken = item.tokens?.easingToken ? stringLiteral(item.tokens.easingToken) : "nil";
    const sourceRule = reduced.sourceRule ? stringLiteral(reduced.sourceRule) : "nil";
    return `        Motion(
            id: .${swiftMotionIdCase(item.id)},
            durationMs: ${item.durationMs},
            easing: .${swiftEasingCase(item.easing)},
            tokens: MotionTokens(durationToken: ${durationToken}, easingToken: ${easingToken}),
            guardRules: ${swiftStringArray(guardRules)},
            reducedMotion: MotionReducedMotion(forceZeroDuration: ${reduced.forceZeroDuration}, directManipulation: ${reduced.directManipulation}, sourceRule: ${sourceRule}),
            deprecated: ${item.deprecated === true ? "true" : "false"}
        )`;
  });
  return `// AUTO-GENERATED by tools/codegen/generate.mjs. DO NOT EDIT.
// Source: contracts/motion.schema.json + fixtures/motion.fixtures.json
import Foundation

public enum MotionId: String, Codable, CaseIterable, Sendable {
${ids.map((id) => `    case ${swiftMotionIdCase(id)} = "${id}"`).join("\n")}
}

public enum MotionEasing: String, Codable, CaseIterable, Sendable {
${easings.map((e) => `    case ${swiftEasingCase(e)} = "${e}"`).join("\n")}
}

public struct Motion: Codable, Equatable, Sendable {
    public let id: MotionId
    public let durationMs: Int
    public let easing: MotionEasing
    public var tokens: MotionTokens?
    public var guardRules: [String]?
    public var reducedMotion: MotionReducedMotion?
    public var deprecated: Bool?
}

public struct MotionTokens: Codable, Equatable, Sendable {
    public var durationToken: String?
    public var easingToken: String?
}

public struct MotionReducedMotion: Codable, Equatable, Sendable {
    public var forceZeroDuration: Bool
    public var directManipulation: Bool
    public var sourceRule: String?
}

public enum MotionSpecRegistry {
    public static let all: [Motion] = [
${registry.join(",\n")}
    ]

    public static let byId: [MotionId: Motion] = Dictionary(uniqueKeysWithValues: all.map { ($0.id, $0) })

    public static func spec(for id: MotionId) -> Motion? {
        byId[id]
    }
}
`;
}

function genSwiftToken(schema, fixtures) {
  const categories = extractEnum(schema, "category");
  const registry = fixtures.map((item) => {
    const platforms = item.platforms
      ? `TokenPlatforms(swift: ${item.platforms.swift ? stringLiteral(item.platforms.swift) : "nil"}, kotlin: ${item.platforms.kotlin ? stringLiteral(item.platforms.kotlin) : "nil"}, arkts: ${item.platforms.arkts ? stringLiteral(item.platforms.arkts) : "nil"})`
      : "nil";
    return `        Token(
            name: ${stringLiteral(item.name)},
            category: .${toCamelCase(item.category)},
            value: ${stringLiteral(item.value)},
            platforms: ${platforms},
            deprecated: ${item.deprecated === true ? "true" : "false"}
        )`;
  });
  return `// AUTO-GENERATED by tools/codegen/generate.mjs. DO NOT EDIT.
// Source: contracts/token.schema.json + fixtures/token.fixtures.json
import Foundation

public enum TokenCategory: String, Codable, CaseIterable, Sendable {
${categories.map((c) => `    case ${toCamelCase(c)} = "${c}"`).join("\n")}
}

public struct Token: Codable, Equatable, Sendable {
    public let name: String
    public let category: TokenCategory
    public let value: String
    public var platforms: TokenPlatforms?
    public var deprecated: Bool?
}

public struct TokenPlatforms: Codable, Equatable, Sendable {
    public var swift: String?
    public var kotlin: String?
    public var arkts: String?
}

public enum TokenRegistry {
    public static let all: [Token] = [
${registry.join(",\n")}
    ]

    public static let byName: [String: Token] = Dictionary(uniqueKeysWithValues: all.map { ($0.name, $0) })

    public static func token(named name: String) -> Token? {
        byName[name]
    }
}
`;
}

// --- 生成 Kotlin ---
function genKotlinEnum(name, values, valueTransform = (v) => v) {
  const cases = values.map((v) => {
    const ident = toPascalCase(String(v)).replace(/[^A-Za-z0-9_]/g, "_");
    return `    @SerialName("${v}")\n    ${ident}`;
  });
  return `@Serializable
enum class ${name} {
${cases.join(",\n")}
}`;
}

function genKotlinRoute(schema) {
  const ids = extractEnum(schema, "id");
  const shells = extractEnum(schema, "shell");
  return `// AUTO-GENERATED by tools/codegen/generate.mjs. DO NOT EDIT.
// Source: contracts/route.schema.json
package io.reader.ui.contract

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

${genKotlinEnum("RouteId", ids)}

${genKotlinEnum("RouteShell", shells)}

${genKotlinEnum("MainTab", ["bookshelf", "discover", "rss", "settings"])}

@Serializable
data class Route(
    val id: RouteId,
    val shell: RouteShell,
    val params: Map<String, String> = emptyMap(),
    val mainTab: MainTab? = null,
    val deprecated: Boolean = false,
    val replacedBy: String? = null
)
`;
}

function genKotlinUiEvent(schema) {
  const types = extractEnum(schema, "type");
  return `// AUTO-GENERATED by tools/codegen/generate.mjs. DO NOT EDIT.
// Source: contracts/ui-event.schema.json
package io.reader.ui.contract

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.json.JsonElement

${genKotlinEnum("UiEventType", types)}

@Serializable
data class UiEvent(
    val type: UiEventType,
    val payload: Map<String, JsonElement> = emptyMap(),
    val timestamp: String? = null,
    val correlationId: String? = null
)
`;
}

function genKotlinUiState(schema) {
  return `// AUTO-GENERATED by tools/codegen/generate.mjs. DO NOT EDIT.
// Source: contracts/ui-state.schema.json
package io.reader.ui.contract

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.json.JsonElement

${genKotlinEnum("ReaderMode", ["default", "loading", "empty", "error", "offline", "permission"])}

${genKotlinEnum("Overlay", ["settings", "reader-control", "directory", "tts", "appearance", "auto-page", "content-search", "content-replacement", "source-switch", "book-action", "sort-filter", "group-management", "local-import", "batch-management", "reader-night-state", "reader-debug-info", "reader-book-cache", "keyboard", "dialog", "sheet", "toast"])}

${genKotlinEnum("ActiveSession", ["reading", "tts", "auto-page"])}

${genKotlinEnum("PageState", ["default", "loading", "empty", "error", "offline", "permission", "cover-mode", "list-mode", "shelf-empty", "no-cover", "long-title", "switching-source-type", "source-empty", "source-unavailable", "network-failed", "refreshing", "no-subscription", "no-unread", "local-data-loading", "no-backup", "permission-missing", "topbar-action"])}

@Serializable
data class UiError(
    val code: String,
    val message: String,
    val retryable: Boolean = false
)

@Serializable
data class RouteRef(
    val id: String,
    val params: Map<String, String> = emptyMap(),
    val stack: List<RouteRef>? = null
)

@Serializable
data class BookshelfUiState(
    val viewMode: String? = null,
    val selectedGroupId: String? = null,
    val sortKey: String? = null,
    val sortOrder: String? = null,
    val filterKeys: List<String>? = null
)

@Serializable
data class DiscoverUiState(
    val filter: String? = null,
    val sort: String? = null,
    val sortOpen: Boolean? = null,
    val sourceType: String? = null,
    val sourceEnabled: Map<String, Boolean>? = null
)

@Serializable
data class ReaderUiState(
    val turnDirection: String? = null,
    val pageIndex: Int? = null,
    val chapterIndex: Int? = null,
    val chapterProgress: Double? = null,
    val chapterDownloads: Map<String, String>? = null,
    val tts: Map<String, JsonElement>? = null,
    val settings: Map<String, JsonElement>? = null,
    val typography: Map<String, JsonElement>? = null,
    val textSelectionOpen: Boolean? = null,
    val selectedText: String? = null,
    val sessionCapsuleSnapshot: Map<String, JsonElement>? = null,
    val controlSpaceSnapshot: Map<String, JsonElement>? = null,
    val autoPageCountdown: Double? = null,
    val dockOffsets: Map<String, Double>? = null,
    val entryMotion: String? = null
)

@Serializable
data class SettingsUiState(
    val overlay: String? = null,
    val expandedOption: String? = null,
    val restoreAvailableScopes: List<String>? = null,
    val restoreSelectedScopes: List<String>? = null
)

@Serializable
data class MotionUiState(
    val overlaySequence: String? = null,
    val overlayRole: String? = null,
    val overlayAction: String? = null,
    val overlayFocusReturn: String? = null,
    val overlayReturnTarget: String? = null,
    val viewportOrientationMotion: String? = null,
    val viewportOrientationSequence: String? = null,
    val viewportOrientationTimer: Double? = null,
    val interruptMotion: String? = null,
    val interruptSequence: String? = null,
    val interruptTimer: Double? = null,
    val dropdownMotion: String? = null,
    val dropdownSwitchMotion: String? = null,
    val dropdownSwitchSequence: String? = null,
    val dropdownSwitchTimer: Double? = null,
    val segmentMotion: String? = null,
    val asyncRouteRequest: String? = null,
    val asyncResultMotion: String? = null,
    val asyncResultSequence: String? = null
)

@Serializable
data class FirstOpenUiState(
    val hasPlayed: Boolean? = null,
    val motionTimer: Double? = null
)

@Serializable
data class UiState(
    val route: RouteRef,
    val tab: MainTab,
    val readerMode: ReaderMode,
    val overlay: Overlay? = null,
    val activeSession: ActiveSession? = null,
    val focusTarget: String? = null,
    val loading: Boolean,
    val error: UiError? = null,
    val reducedMotion: Boolean = false,
    val pageState: PageState? = null,
    val bookshelf: BookshelfUiState? = null,
    val discover: DiscoverUiState? = null,
    val reader: ReaderUiState? = null,
    val settings: SettingsUiState? = null,
    val motion: MotionUiState? = null,
    val firstOpen: FirstOpenUiState? = null
)
`;
}

function genKotlinViewState(schema) {
  const types = schema.$defs.Component.properties.type.enum || [];
  return `// AUTO-GENERATED by tools/codegen/generate.mjs. DO NOT EDIT.
// Source: contracts/view-state.schema.json
package io.reader.ui.contract

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.json.JsonElement

${genKotlinEnum("ComponentType", types)}

@Serializable
data class ViewStateComponent(
    val type: ComponentType,
    val id: String? = null,
    val props: Map<String, JsonElement>? = null,
    val children: List<ViewStateComponent>? = null
)

@Serializable
data class ViewState(
    val routeId: String,
    val pageState: PageState,
    val context: Map<String, JsonElement>? = null,
    val components: List<ViewStateComponent>
)
`;
}

function genKotlinMotion(schema, fixtures) {
  const ids = extractEnum(schema, "id");
  const easings = extractEnum(schema, "easing");
  const registry = fixtures.map((item) => {
    const guardRules = Array.isArray(item.guardRules) ? item.guardRules : [];
    const reduced = reducedMotionInfo(item);
    const sourceRule = reduced.sourceRule ? stringLiteral(reduced.sourceRule) : "null";
    return `    Motion(
        id = MotionId.${kotlinCase(item.id)},
        durationMs = ${item.durationMs},
        easing = MotionEasing.${kotlinCase(item.easing)},
        tokens = MotionTokens(durationToken = ${item.tokens?.durationToken ? stringLiteral(item.tokens.durationToken) : "null"}, easingToken = ${item.tokens?.easingToken ? stringLiteral(item.tokens.easingToken) : "null"}),
        guardRules = ${kotlinStringList(guardRules)},
        reducedMotion = MotionReducedMotion(forceZeroDuration = ${reduced.forceZeroDuration}, directManipulation = ${reduced.directManipulation}, sourceRule = ${sourceRule}),
        deprecated = ${item.deprecated === true ? "true" : "false"}
    )`;
  });
  return `// AUTO-GENERATED by tools/codegen/generate.mjs. DO NOT EDIT.
// Source: contracts/motion.schema.json + fixtures/motion.fixtures.json
package io.reader.ui.contract

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

${genKotlinEnum("MotionId", ids)}

${genKotlinEnum("MotionEasing", easings)}

@Serializable
data class MotionTokens(
    val durationToken: String? = null,
    val easingToken: String? = null
)

@Serializable
data class Motion(
    val id: MotionId,
    val durationMs: Int,
    val easing: MotionEasing,
    val tokens: MotionTokens? = null,
    val guardRules: List<String>? = null,
    val reducedMotion: MotionReducedMotion? = null,
    val deprecated: Boolean = false
)

@Serializable
data class MotionReducedMotion(
    val forceZeroDuration: Boolean,
    val directManipulation: Boolean,
    val sourceRule: String? = null
)

object MotionSpecRegistry {
    val all: List<Motion> = listOf(
${registry.join(",\n")}
    )

    val byId: Map<MotionId, Motion> = all.associateBy { it.id }

    fun spec(id: MotionId): Motion? = byId[id]
}
`;
}

function genKotlinToken(schema, fixtures) {
  const categories = extractEnum(schema, "category");
  const registry = fixtures.map((item) => {
    const platforms = item.platforms
      ? `TokenPlatforms(swift = ${item.platforms.swift ? stringLiteral(item.platforms.swift) : "null"}, kotlin = ${item.platforms.kotlin ? stringLiteral(item.platforms.kotlin) : "null"}, arkts = ${item.platforms.arkts ? stringLiteral(item.platforms.arkts) : "null"})`
      : "null";
    return `    Token(
        name = ${stringLiteral(item.name)},
        category = TokenCategory.${kotlinCase(item.category)},
        value = ${stringLiteral(item.value)},
        platforms = ${platforms},
        deprecated = ${item.deprecated === true ? "true" : "false"}
    )`;
  });
  return `// AUTO-GENERATED by tools/codegen/generate.mjs. DO NOT EDIT.
// Source: contracts/token.schema.json + fixtures/token.fixtures.json
package io.reader.ui.contract

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

${genKotlinEnum("TokenCategory", categories)}

@Serializable
data class TokenPlatforms(
    val swift: String? = null,
    val kotlin: String? = null,
    val arkts: String? = null
)

@Serializable
data class Token(
    val name: String,
    val category: TokenCategory,
    val value: String,
    val platforms: TokenPlatforms? = null,
    val deprecated: Boolean = false
)

object TokenRegistry {
    val all: List<Token> = listOf(
${registry.join(",\n")}
    )

    val byName: Map<String, Token> = all.associateBy { it.name }

    fun token(name: String): Token? = byName[name]
}
`;
}

// --- 生成 ArkTS ---
function genArkTsEnum(name, values) {
  const cases = values.map((v) => `  | "${v}"`).join("\n");
  return `export type ${name} =\n${cases};`;
}

function genArkTsRoute(schema) {
  const ids = extractEnum(schema, "id");
  const shells = extractEnum(schema, "shell");
  return `// AUTO-GENERATED by tools/codegen/generate.mjs. DO NOT EDIT.
// Source: contracts/route.schema.json
${genArkTsEnum("RouteId", ids)}

${genArkTsEnum("RouteShell", shells)}

${genArkTsEnum("MainTab", ["bookshelf", "discover", "rss", "settings"])}

export interface Route {
  id: RouteId;
  shell: RouteShell;
  params?: Record<string, string>;
  mainTab?: MainTab;
  deprecated?: boolean;
  replacedBy?: string;
}
`;
}

function genArkTsUiEvent(schema) {
  const types = extractEnum(schema, "type");
  return `// AUTO-GENERATED by tools/codegen/generate.mjs. DO NOT EDIT.
// Source: contracts/ui-event.schema.json
${genArkTsEnum("UiEventType", types)}

export interface UiEvent {
  type: UiEventType;
  payload: Record<string, object | string | number | boolean | null>;
  timestamp?: string;
  correlationId?: string;
}
`;
}

function genArkTsUiState(schema) {
  return `// AUTO-GENERATED by tools/codegen/generate.mjs. DO NOT EDIT.
// Source: contracts/ui-state.schema.json
${genArkTsEnum("ReaderMode", ["default", "loading", "empty", "error", "offline", "permission"])}

${genArkTsEnum("Overlay", ["settings", "reader-control", "directory", "tts", "appearance", "auto-page", "content-search", "content-replacement", "source-switch", "book-action", "sort-filter", "group-management", "local-import", "batch-management", "reader-night-state", "reader-debug-info", "reader-book-cache", "keyboard", "dialog", "sheet", "toast"])}

${genArkTsEnum("ActiveSession", ["reading", "tts", "auto-page"])}

${genArkTsEnum("PageState", ["default", "loading", "empty", "error", "offline", "permission", "cover-mode", "list-mode", "shelf-empty", "no-cover", "long-title", "switching-source-type", "source-empty", "source-unavailable", "network-failed", "refreshing", "no-subscription", "no-unread", "local-data-loading", "no-backup", "permission-missing", "topbar-action"])}

export interface UiError {
  code: string;
  message: string;
  retryable?: boolean;
}

export interface RouteRef {
  id: string;
  params?: Record<string, string>;
  stack?: RouteRef[];
}

export interface BookshelfUiState {
  viewMode?: string;
  selectedGroupId?: string;
  sortKey?: string;
  sortOrder?: string;
  filterKeys?: string[];
}

export interface DiscoverUiState {
  filter?: string;
  sort?: string;
  sortOpen?: boolean;
  sourceType?: string;
  sourceEnabled?: Record<string, boolean>;
}

export interface ReaderUiState {
  turnDirection?: string;
  pageIndex?: number;
  chapterIndex?: number;
  chapterProgress?: number;
  chapterDownloads?: Record<string, string>;
  tts?: Record<string, object>;
  settings?: Record<string, object>;
  typography?: Record<string, object>;
  textSelectionOpen?: boolean;
  selectedText?: string;
  sessionCapsuleSnapshot?: Record<string, object>;
  controlSpaceSnapshot?: Record<string, object>;
  autoPageCountdown?: number;
  dockOffsets?: Record<string, number>;
  entryMotion?: string;
}

export interface SettingsUiState {
  overlay?: string;
  expandedOption?: string;
  restoreAvailableScopes?: string[];
  restoreSelectedScopes?: string[];
}

export interface MotionUiState {
  overlaySequence?: string;
  overlayRole?: string;
  overlayAction?: string;
  overlayFocusReturn?: string;
  overlayReturnTarget?: string;
  viewportOrientationMotion?: string;
  viewportOrientationSequence?: string;
  viewportOrientationTimer?: number;
  interruptMotion?: string;
  interruptSequence?: string;
  interruptTimer?: number;
  dropdownMotion?: string;
  dropdownSwitchMotion?: string;
  dropdownSwitchSequence?: string;
  dropdownSwitchTimer?: number;
  segmentMotion?: string;
  asyncRouteRequest?: string;
  asyncResultMotion?: string;
  asyncResultSequence?: string;
}

export interface FirstOpenUiState {
  hasPlayed?: boolean;
  motionTimer?: number;
}

export interface UiState {
  route: RouteRef;
  tab: MainTab;
  readerMode: ReaderMode;
  overlay?: Overlay;
  activeSession?: ActiveSession;
  focusTarget?: string;
  loading: boolean;
  error?: UiError;
  reducedMotion: boolean;
  pageState?: PageState;
  bookshelf?: BookshelfUiState;
  discover?: DiscoverUiState;
  reader?: ReaderUiState;
  settings?: SettingsUiState;
  motion?: MotionUiState;
  firstOpen?: FirstOpenUiState;
}
`;
}

function genArkTsViewState(schema) {
  const types = schema.$defs.Component.properties.type.enum || [];
  return `// AUTO-GENERATED by tools/codegen/generate.mjs. DO NOT EDIT.
// Source: contracts/view-state.schema.json
${genArkTsEnum("ComponentType", types)}

export interface ViewStateComponent {
  type: ComponentType;
  id?: string;
  props?: Record<string, object | string | number | boolean | null>;
  children?: ViewStateComponent[];
}

export interface ViewState {
  routeId: string;
  pageState: PageState;
  context?: Record<string, object | string | number | boolean | null>;
  components: ViewStateComponent[];
}
`;
}

function genArkTsMotion(schema, fixtures) {
  const ids = extractEnum(schema, "id");
  const easings = extractEnum(schema, "easing");
  const registry = fixtures.map((item) => {
    const guardRules = Array.isArray(item.guardRules) ? item.guardRules : [];
    const reduced = reducedMotionInfo(item);
    const sourceRule = reduced.sourceRule ? stringLiteral(reduced.sourceRule) : "undefined";
    return `  ${stringLiteral(item.id)}: {
    id: ${stringLiteral(item.id)},
    durationMs: ${item.durationMs},
    easing: ${stringLiteral(item.easing)},
    tokens: { durationToken: ${item.tokens?.durationToken ? stringLiteral(item.tokens.durationToken) : "undefined"}, easingToken: ${item.tokens?.easingToken ? stringLiteral(item.tokens.easingToken) : "undefined"} },
    guardRules: ${arkTsStringArray(guardRules)},
    reducedMotion: { forceZeroDuration: ${reduced.forceZeroDuration}, directManipulation: ${reduced.directManipulation}, sourceRule: ${sourceRule} },
    deprecated: ${item.deprecated === true ? "true" : "false"}
  }`;
  });
  return `// AUTO-GENERATED by tools/codegen/generate.mjs. DO NOT EDIT.
// Source: contracts/motion.schema.json + fixtures/motion.fixtures.json
${genArkTsEnum("MotionId", ids)}

${genArkTsEnum("MotionEasing", easings)}

export interface MotionTokens {
  durationToken?: string;
  easingToken?: string;
}

export interface Motion {
  id: MotionId;
  durationMs: number;
  easing: MotionEasing;
  tokens?: MotionTokens;
  guardRules?: string[];
  reducedMotion?: MotionReducedMotion;
  deprecated?: boolean;
}

export interface MotionReducedMotion {
  forceZeroDuration: boolean;
  directManipulation: boolean;
  sourceRule?: string;
}

export const motionSpecRegistry: Record<MotionId, Motion> = {
${registry.join(",\n")}
};

export const motionSpecs: Motion[] = Object.values(motionSpecRegistry);

export function getMotionSpec(id: MotionId): Motion | undefined {
  return motionSpecRegistry[id];
}
`;
}

function genArkTsToken(schema, fixtures) {
  const categories = extractEnum(schema, "category");
  const registry = fixtures.map((item) => {
    const platforms = item.platforms
      ? `{ swift: ${item.platforms.swift ? stringLiteral(item.platforms.swift) : "undefined"}, kotlin: ${item.platforms.kotlin ? stringLiteral(item.platforms.kotlin) : "undefined"}, arkts: ${item.platforms.arkts ? stringLiteral(item.platforms.arkts) : "undefined"} }`
      : "undefined";
    return `  ${stringLiteral(item.name)}: {
    name: ${stringLiteral(item.name)},
    category: ${stringLiteral(item.category)},
    value: ${stringLiteral(item.value)},
    platforms: ${platforms},
    deprecated: ${item.deprecated === true ? "true" : "false"}
  }`;
  });
  return `// AUTO-GENERATED by tools/codegen/generate.mjs. DO NOT EDIT.
// Source: contracts/token.schema.json + fixtures/token.fixtures.json
${genArkTsEnum("TokenCategory", categories)}

export interface TokenPlatforms {
  swift?: string;
  kotlin?: string;
  arkts?: string;
}

export interface Token {
  name: string;
  category: TokenCategory;
  value: string;
  platforms?: TokenPlatforms;
  deprecated?: boolean;
}

export const tokenRegistry: Record<string, Token> = {
${registry.join(",\n")}
};

export const tokens: Token[] = Object.values(tokenRegistry);

export function getToken(name: string): Token | undefined {
  return tokenRegistry[name];
}
`;
}

// --- Phase 2: CoreCommand / CoreEvent / HostRequest / ProgressLocation / Content / SyncConflict ---

function genSwiftCoreCommand(schema) {
  const types = extractEnum(schema, "type");
  return `// AUTO-GENERATED by tools/codegen/generate.mjs. DO NOT EDIT.
// Source: contracts/core-command.schema.json
import Foundation

public enum CoreCommandType: String, Codable, CaseIterable, Sendable {
${types.map((t) => `    case ${t.replace(/[.]/g, "_")} = "${t}"`).join("\n")}
}

public struct CoreCommand: Codable, Equatable, Sendable {
    public let type: CoreCommandType
    public var payload: [String: AnyCodable]
    public var correlationId: String?
    public var requestId: String?

    public init(type: CoreCommandType, payload: [String: AnyCodable] = [:], correlationId: String? = nil, requestId: String? = nil) {
        self.type = type
        self.payload = payload
        self.correlationId = correlationId
        self.requestId = requestId
    }
}
`;
}

function genSwiftCoreEvent(schema) {
  const types = extractEnum(schema, "type");
  return `// AUTO-GENERATED by tools/codegen/generate.mjs. DO NOT EDIT.
// Source: contracts/core-event.schema.json
import Foundation

public enum CoreEventType: String, Codable, CaseIterable, Sendable {
${types.map((t) => `    case ${t.replace(/[.]/g, "_")} = "${t}"`).join("\n")}
}

public struct CoreEvent: Codable, Equatable, Sendable {
    public let type: CoreEventType
    public var payload: [String: AnyCodable]
    public var correlationId: String?
    public var requestId: String?
    public var timestamp: Date?

    public init(type: CoreEventType, payload: [String: AnyCodable] = [:], correlationId: String? = nil, requestId: String? = nil) {
        self.type = type
        self.payload = payload
        self.correlationId = correlationId
        self.requestId = requestId
    }
}
`;
}

function genSwiftHostRequest(schema) {
  const types = extractEnum(schema, "type");
  const initiators = extractEnum(schema, "initiator");
  return `// AUTO-GENERATED by tools/codegen/generate.mjs. DO NOT EDIT.
// Source: contracts/host-request.schema.json
import Foundation

public enum HostRequestType: String, Codable, CaseIterable, Sendable {
${types.map((t) => `    case ${t.replace(/[.-]/g, "_")} = "${t}"`).join("\n")}
}

public enum HostInitiator: String, Codable, CaseIterable, Sendable {
${initiators.map((i) => `    case ${i} = "${i}"`).join("\n")}
}

public struct HostRequest: Codable, Equatable, Sendable {
    public let type: HostRequestType
    public var payload: [String: AnyCodable]
    public var correlationId: String?
    public var requestId: String?
    public var initiator: HostInitiator?

    public init(type: HostRequestType, payload: [String: AnyCodable] = [:], correlationId: String? = nil, requestId: String? = nil, initiator: HostInitiator? = nil) {
        self.type = type
        self.payload = payload
        self.correlationId = correlationId
        self.requestId = requestId
        self.initiator = initiator
    }
}
`;
}

function genSwiftProgressLocation(schema) {
  const locatorTypes = schema.properties.locator.properties.type.enum || [];
  const sources = extractEnum(schema, "source");
  return `// AUTO-GENERATED by tools/codegen/generate.mjs. DO NOT EDIT.
// Source: contracts/progress-location.schema.json
import Foundation

public enum LocatorType: String, Codable, CaseIterable, Sendable {
${locatorTypes.map((t) => `    case ${t.replace(/-/g, "_")} = "${t}"`).join("\n")}
}

public enum ProgressSource: String, Codable, CaseIterable, Sendable {
${sources.map((s) => `    case ${s.replace(/-/g, "_")} = "${s}"`).join("\n")}
}

public struct Locator: Codable, Equatable, Sendable {
    public let type: LocatorType
    public var charOffset: Int?
    public var paragraphIndex: Int?
    public var selector: String?
    public var range: LocatorRange?
}

public struct LocatorRange: Codable, Equatable, Sendable {
    public var start: [String: AnyCodable]?
    public var end: [String: AnyCodable]?
}

public struct ProgressLocation: Codable, Equatable, Sendable {
    public let bookId: String
    public let chapterIndex: Int
    public var chapterId: String?
    public let locator: Locator
    public var progress: Double?
    public var pageIndex: Int?
    public var updatedAt: Date?
    public var source: ProgressSource?
}
`;
}

function genSwiftContent(schema) {
  const blockTypes = schema.$defs.Block.properties.type.enum || [];
  return `// AUTO-GENERATED by tools/codegen/generate.mjs. DO NOT EDIT.
// Source: contracts/content.schema.json
import Foundation

public enum BlockType: String, Codable, CaseIterable, Sendable {
${blockTypes.map((t) => `    case ${t.replace(/-/g, "_")} = "${t}"`).join("\n")}
}

public struct ContentBlock: Codable, Equatable, Sendable {
    public let type: BlockType
    public var text: String?
    public var level: Int?
    public var url: String?
    public var alt: String?
    public var items: [String]?
    public var ordered: Bool?
    public var language: String?
}

public struct ContentMeta: Codable, Equatable, Sendable {
    public var wordCount: Int?
    public var charset: String?
    public var sourceUrl: String?
    public var fetchedAt: Date?
}

public struct Content: Codable, Equatable, Sendable {
    public let bookId: String
    public let chapterId: String
    public var chapterIndex: Int
    public var chapterTitle: String?
    public let blocks: [ContentBlock]
    public var meta: ContentMeta?
    public var cached: Bool?
}
`;
}

function genSwiftSyncConflict(schema) {
  const types = extractEnum(schema, "type");
  const resolutions = extractEnum(schema, "resolution").filter((v) => v !== null);
  return `// AUTO-GENERATED by tools/codegen/generate.mjs. DO NOT EDIT.
// Source: contracts/sync-conflict.schema.json
import Foundation

public enum SyncConflictType: String, Codable, CaseIterable, Sendable {
${types.map((t) => `    case ${t.replace(/-/g, "_")} = "${t}"`).join("\n")}
}

public enum SyncConflictResolution: String, Codable, CaseIterable, Sendable {
${resolutions.map((r) => `    case ${r.replace(/-/g, "_")} = "${r}"`).join("\n")}
}

public struct SyncConflict: Codable, Equatable, Sendable {
    public let conflictId: String
    public let bookId: String
    public let type: SyncConflictType
    public let local: [String: AnyCodable]
    public let remote: [String: AnyCodable]
    public var localUpdatedAt: Date?
    public var remoteUpdatedAt: Date?
    public var resolution: SyncConflictResolution?
    public var mergeHint: [String: AnyCodable]?
    public var detectedAt: Date?
}
`;
}

function genKotlinCoreCommand(schema) {
  const types = extractEnum(schema, "type");
  return `// AUTO-GENERATED by tools/codegen/generate.mjs. DO NOT EDIT.
// Source: contracts/core-command.schema.json
package io.reader.ui.contract

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.json.JsonElement

${genKotlinEnum("CoreCommandType", types)}

@Serializable
data class CoreCommand(
    val type: CoreCommandType,
    val payload: Map<String, JsonElement> = emptyMap(),
    val correlationId: String? = null,
    val requestId: String? = null
)
`;
}

function genKotlinCoreEvent(schema) {
  const types = extractEnum(schema, "type");
  return `// AUTO-GENERATED by tools/codegen/generate.mjs. DO NOT EDIT.
// Source: contracts/core-event.schema.json
package io.reader.ui.contract

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.json.JsonElement

${genKotlinEnum("CoreEventType", types)}

@Serializable
data class CoreEvent(
    val type: CoreEventType,
    val payload: Map<String, JsonElement> = emptyMap(),
    val correlationId: String? = null,
    val requestId: String? = null,
    val timestamp: String? = null
)
`;
}

function genKotlinHostRequest(schema) {
  const types = extractEnum(schema, "type");
  const initiators = extractEnum(schema, "initiator");
  return `// AUTO-GENERATED by tools/codegen/generate.mjs. DO NOT EDIT.
// Source: contracts/host-request.schema.json
package io.reader.ui.contract

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.json.JsonElement

${genKotlinEnum("HostRequestType", types)}

${genKotlinEnum("HostInitiator", initiators)}

@Serializable
data class HostRequest(
    val type: HostRequestType,
    val payload: Map<String, JsonElement> = emptyMap(),
    val correlationId: String? = null,
    val requestId: String? = null,
    val initiator: HostInitiator? = null
)
`;
}

function genKotlinProgressLocation(schema) {
  const locatorTypes = schema.properties.locator.properties.type.enum || [];
  const sources = extractEnum(schema, "source");
  return `// AUTO-GENERATED by tools/codegen/generate.mjs. DO NOT EDIT.
// Source: contracts/progress-location.schema.json
package io.reader.ui.contract

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.json.JsonElement

${genKotlinEnum("LocatorType", locatorTypes)}

${genKotlinEnum("ProgressSource", sources)}

@Serializable
data class LocatorRange(
    val start: Map<String, JsonElement>? = null,
    val end: Map<String, JsonElement>? = null
)

@Serializable
data class Locator(
    val type: LocatorType,
    val charOffset: Int? = null,
    val paragraphIndex: Int? = null,
    val selector: String? = null,
    val range: LocatorRange? = null
)

@Serializable
data class ProgressLocation(
    val bookId: String,
    val chapterIndex: Int,
    val chapterId: String? = null,
    val locator: Locator,
    val progress: Double? = null,
    val pageIndex: Int? = null,
    val updatedAt: String? = null,
    val source: ProgressSource? = null
)
`;
}

function genKotlinContent(schema) {
  const blockTypes = schema.$defs.Block.properties.type.enum || [];
  return `// AUTO-GENERATED by tools/codegen/generate.mjs. DO NOT EDIT.
// Source: contracts/content.schema.json
package io.reader.ui.contract

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

${genKotlinEnum("BlockType", blockTypes)}

@Serializable
data class ContentBlock(
    val type: BlockType,
    val text: String? = null,
    val level: Int? = null,
    val url: String? = null,
    val alt: String? = null,
    val items: List<String>? = null,
    val ordered: Boolean? = null,
    val language: String? = null
)

@Serializable
data class ContentMeta(
    val wordCount: Int? = null,
    val charset: String? = null,
    val sourceUrl: String? = null,
    val fetchedAt: String? = null
)

@Serializable
data class Content(
    val bookId: String,
    val chapterId: String,
    val chapterIndex: Int,
    val chapterTitle: String? = null,
    val blocks: List<ContentBlock>,
    val meta: ContentMeta? = null,
    val cached: Boolean = false
)
`;
}

function genKotlinSyncConflict(schema) {
  const types = extractEnum(schema, "type");
  const resolutions = extractEnum(schema, "resolution").filter((v) => v !== null);
  return `// AUTO-GENERATED by tools/codegen/generate.mjs. DO NOT EDIT.
// Source: contracts/sync-conflict.schema.json
package io.reader.ui.contract

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.json.JsonElement

${genKotlinEnum("SyncConflictType", types)}

${genKotlinEnum("SyncConflictResolution", resolutions)}

@Serializable
data class SyncConflict(
    val conflictId: String,
    val bookId: String,
    val type: SyncConflictType,
    val local: Map<String, JsonElement>,
    val remote: Map<String, JsonElement>,
    val localUpdatedAt: String? = null,
    val remoteUpdatedAt: String? = null,
    val resolution: SyncConflictResolution? = null,
    val mergeHint: Map<String, JsonElement>? = null,
    val detectedAt: String? = null
)
`;
}

function genArkTsCoreCommand(schema) {
  const types = extractEnum(schema, "type");
  return `// AUTO-GENERATED by tools/codegen/generate.mjs. DO NOT EDIT.
// Source: contracts/core-command.schema.json
${genArkTsEnum("CoreCommandType", types)}

export interface CoreCommand {
  type: CoreCommandType;
  payload: Record<string, object | string | number | boolean | null>;
  correlationId?: string;
  requestId?: string;
}
`;
}

function genArkTsCoreEvent(schema) {
  const types = extractEnum(schema, "type");
  return `// AUTO-GENERATED by tools/codegen/generate.mjs. DO NOT EDIT.
// Source: contracts/core-event.schema.json
${genArkTsEnum("CoreEventType", types)}

export interface CoreEvent {
  type: CoreEventType;
  payload: Record<string, object | string | number | boolean | null>;
  correlationId?: string;
  requestId?: string;
  timestamp?: string;
}
`;
}

function genArkTsHostRequest(schema) {
  const types = extractEnum(schema, "type");
  const initiators = extractEnum(schema, "initiator");
  return `// AUTO-GENERATED by tools/codegen/generate.mjs. DO NOT EDIT.
// Source: contracts/host-request.schema.json
${genArkTsEnum("HostRequestType", types)}

${genArkTsEnum("HostInitiator", initiators)}

export interface HostRequest {
  type: HostRequestType;
  payload: Record<string, object | string | number | boolean | null>;
  correlationId?: string;
  requestId?: string;
  initiator?: HostInitiator;
}
`;
}

function genArkTsProgressLocation(schema) {
  const locatorTypes = schema.properties.locator.properties.type.enum || [];
  const sources = extractEnum(schema, "source");
  return `// AUTO-GENERATED by tools/codegen/generate.mjs. DO NOT EDIT.
// Source: contracts/progress-location.schema.json
${genArkTsEnum("LocatorType", locatorTypes)}

${genArkTsEnum("ProgressSource", sources)}

export interface LocatorRange {
  start?: Record<string, object | string | number | boolean | null>;
  end?: Record<string, object | string | number | boolean | null>;
}

export interface Locator {
  type: LocatorType;
  charOffset?: number;
  paragraphIndex?: number;
  selector?: string;
  range?: LocatorRange;
}

export interface ProgressLocation {
  bookId: string;
  chapterIndex: number;
  chapterId?: string;
  locator: Locator;
  progress?: number;
  pageIndex?: number;
  updatedAt?: string;
  source?: ProgressSource;
}
`;
}

function genArkTsContent(schema) {
  const blockTypes = schema.$defs.Block.properties.type.enum || [];
  return `// AUTO-GENERATED by tools/codegen/generate.mjs. DO NOT EDIT.
// Source: contracts/content.schema.json
${genArkTsEnum("BlockType", blockTypes)}

export interface ContentBlock {
  type: BlockType;
  text?: string;
  level?: number;
  url?: string;
  alt?: string;
  items?: string[];
  ordered?: boolean;
  language?: string;
}

export interface ContentMeta {
  wordCount?: number;
  charset?: string;
  sourceUrl?: string;
  fetchedAt?: string;
}

export interface Content {
  bookId: string;
  chapterId: string;
  chapterIndex: number;
  chapterTitle?: string;
  blocks: ContentBlock[];
  meta?: ContentMeta;
  cached?: boolean;
}
`;
}

function genArkTsSyncConflict(schema) {
  const types = extractEnum(schema, "type");
  const resolutions = extractEnum(schema, "resolution").filter((v) => v !== null);
  return `// AUTO-GENERATED by tools/codegen/generate.mjs. DO NOT EDIT.
// Source: contracts/sync-conflict.schema.json
${genArkTsEnum("SyncConflictType", types)}

${genArkTsEnum("SyncConflictResolution", resolutions)}

export interface SyncConflict {
  conflictId: string;
  bookId: string;
  type: SyncConflictType;
  local: Record<string, object | string | number | boolean | null>;
  remote: Record<string, object | string | number | boolean | null>;
  localUpdatedAt?: string;
  remoteUpdatedAt?: string;
  resolution?: SyncConflictResolution;
  mergeHint?: Record<string, object | string | number | boolean | null>;
  detectedAt?: string;
}
`;
}

// --- Phase 1 收尾: StateRule ---

function genSwiftStateRule(schema) {
  const kinds = extractEnum(schema, "kind");
  const severities = extractEnum(schema, "severity");
  const sliceValues = schema.properties.target.properties.slices.items.enum || [];
  return `// AUTO-GENERATED by tools/codegen/generate.mjs. DO NOT EDIT.
// Source: contracts/state-rule.schema.json
import Foundation

public enum StateRuleKind: String, Codable, CaseIterable, Sendable {
${kinds.map((k) => `    case ${k.replace(/-/g, "_")} = "${k}"`).join("\n")}
}

public enum StateRuleSeverity: String, Codable, CaseIterable, Sendable {
${severities.map((s) => `    case ${s} = "${s}"`).join("\n")}
}

public enum StateRuleSlice: String, Codable, CaseIterable, Sendable {
${sliceValues.map((s) => `    case ${s.replace(/-/g, "_")} = "${s}"`).join("\n")}
}

public struct StateRuleTarget: Codable, Equatable, Sendable {
    public let fields: [String]
    public var slices: [StateRuleSlice]?

    public init(fields: [String], slices: [StateRuleSlice]? = nil) {
        self.fields = fields
        self.slices = slices
    }
}

public struct StateRuleConstraint: Codable, Equatable, Sendable {
    public var maxNonNull: Int?
    public var guardField: String?
    public var guardValue: AnyCodable?
    public var requiredField: String?
    public var forbiddenField: String?
    public var fromStates: [String]?
    public var toStates: [String]?
    public var description: String?

    public init() {}
}

public struct StateRule: Codable, Equatable, Sendable {
    public let ruleId: String
    public let kind: StateRuleKind
    public let target: StateRuleTarget
    public let constraint: StateRuleConstraint
    public var severity: StateRuleSeverity?
    public var deprecated: Bool?

    public init(ruleId: String, kind: StateRuleKind, target: StateRuleTarget, constraint: StateRuleConstraint, severity: StateRuleSeverity? = nil, deprecated: Bool? = nil) {
        self.ruleId = ruleId
        self.kind = kind
        self.target = target
        self.constraint = constraint
        self.severity = severity
        self.deprecated = deprecated
    }
}
`;
}

function genKotlinStateRule(schema) {
  const kinds = extractEnum(schema, "kind");
  const severities = extractEnum(schema, "severity");
  const sliceValues = schema.properties.target.properties.slices.items.enum || [];
  return `// AUTO-GENERATED by tools/codegen/generate.mjs. DO NOT EDIT.
// Source: contracts/state-rule.schema.json
package io.reader.ui.contract

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.json.JsonElement

${genKotlinEnum("StateRuleKind", kinds)}

${genKotlinEnum("StateRuleSeverity", severities)}

${genKotlinEnum("StateRuleSlice", sliceValues)}

@Serializable
data class StateRuleTarget(
    val fields: List<String>,
    val slices: List<StateRuleSlice>? = null
)

@Serializable
data class StateRuleConstraint(
    val maxNonNull: Int? = null,
    val guardField: String? = null,
    val guardValue: JsonElement? = null,
    val requiredField: String? = null,
    val forbiddenField: String? = null,
    val fromStates: List<String>? = null,
    val toStates: List<String>? = null,
    val description: String? = null
)

@Serializable
data class StateRule(
    val ruleId: String,
    val kind: StateRuleKind,
    val target: StateRuleTarget,
    val constraint: StateRuleConstraint,
    val severity: StateRuleSeverity = StateRuleSeverity.Error,
    val deprecated: Boolean = false
)
`;
}

function genArkTsStateRule(schema) {
  const kinds = extractEnum(schema, "kind");
  const severities = extractEnum(schema, "severity");
  const sliceValues = schema.properties.target.properties.slices.items.enum || [];
  return `// AUTO-GENERATED by tools/codegen/generate.mjs. DO NOT EDIT.
// Source: contracts/state-rule.schema.json
${genArkTsEnum("StateRuleKind", kinds)}

${genArkTsEnum("StateRuleSeverity", severities)}

${genArkTsEnum("StateRuleSlice", sliceValues)}

export interface StateRuleTarget {
  fields: string[];
  slices?: StateRuleSlice[];
}

export interface StateRuleConstraint {
  maxNonNull?: number;
  guardField?: string;
  guardValue?: boolean | string | number | null;
  requiredField?: string;
  forbiddenField?: string;
  fromStates?: string[];
  toStates?: string[];
  description?: string;
}

export interface StateRule {
  ruleId: string;
  kind: StateRuleKind;
  target: StateRuleTarget;
  constraint: StateRuleConstraint;
  severity?: StateRuleSeverity;
  deprecated?: boolean;
}
`;
}

// --- 主流程 ---
function ensureDir(p) {
  if (!existsSync(p)) mkdirSync(p, { recursive: true });
}

function writeFile(p, content) {
  ensureDir(dirname(p));
  writeFileSync(p, content, "utf8");
}

function generate() {
  const routeSchema = loadSchema("route");
  const eventSchema = loadSchema("ui-event");
  const stateSchema = loadSchema("ui-state");
  const viewSchema = loadSchema("view-state");
  const motionSchema = loadSchema("motion");
  const tokenSchema = loadSchema("token");

  // Phase 2 schemas
  const coreCmdSchema = loadSchema("core-command");
  const coreEvtSchema = loadSchema("core-event");
  const hostReqSchema = loadSchema("host-request");
  const progressSchema = loadSchema("progress-location");
  const contentSchema = loadSchema("content");
  const syncConflictSchema = loadSchema("sync-conflict");

  // Phase 1 收尾 schema
  const stateRuleSchema = loadSchema("state-rule");

  const routeFixtures = loadFixtures("route");
  const eventFixtures = loadFixtures("ui-event");
  const motionFixtures = loadFixtures("motion");
  const tokenFixtures = loadFixtures("token");

  // Swift - Phase 1
  writeFile(join(GENERATED_DIR, "swift", "Route.swift"), genSwiftRoute(routeSchema, routeFixtures));
  writeFile(join(GENERATED_DIR, "swift", "UiEvent.swift"), genSwiftUiEvent(eventSchema, eventFixtures));
  writeFile(join(GENERATED_DIR, "swift", "UiState.swift"), genSwiftUiState(stateSchema));
  writeFile(join(GENERATED_DIR, "swift", "ViewState.swift"), genSwiftViewState(viewSchema));
  writeFile(join(GENERATED_DIR, "swift", "Motion.swift"), genSwiftMotion(motionSchema, motionFixtures));
  writeFile(join(GENERATED_DIR, "swift", "Token.swift"), genSwiftToken(tokenSchema, tokenFixtures));

  // Swift - Phase 2
  writeFile(join(GENERATED_DIR, "swift", "CoreCommand.swift"), genSwiftCoreCommand(coreCmdSchema));
  writeFile(join(GENERATED_DIR, "swift", "CoreEvent.swift"), genSwiftCoreEvent(coreEvtSchema));
  writeFile(join(GENERATED_DIR, "swift", "HostRequest.swift"), genSwiftHostRequest(hostReqSchema));
  writeFile(join(GENERATED_DIR, "swift", "ProgressLocation.swift"), genSwiftProgressLocation(progressSchema));
  writeFile(join(GENERATED_DIR, "swift", "Content.swift"), genSwiftContent(contentSchema));
  writeFile(join(GENERATED_DIR, "swift", "SyncConflict.swift"), genSwiftSyncConflict(syncConflictSchema));

  // Swift - Phase 1 收尾
  writeFile(join(GENERATED_DIR, "swift", "StateRule.swift"), genSwiftStateRule(stateRuleSchema));

  // Kotlin - Phase 1
  writeFile(join(GENERATED_DIR, "kotlin", "Route.kt"), genKotlinRoute(routeSchema));
  writeFile(join(GENERATED_DIR, "kotlin", "UiEvent.kt"), genKotlinUiEvent(eventSchema));
  writeFile(join(GENERATED_DIR, "kotlin", "UiState.kt"), genKotlinUiState(stateSchema));
  writeFile(join(GENERATED_DIR, "kotlin", "ViewState.kt"), genKotlinViewState(viewSchema));
  writeFile(join(GENERATED_DIR, "kotlin", "Motion.kt"), genKotlinMotion(motionSchema, motionFixtures));
  writeFile(join(GENERATED_DIR, "kotlin", "Token.kt"), genKotlinToken(tokenSchema, tokenFixtures));

  // Kotlin - Phase 2
  writeFile(join(GENERATED_DIR, "kotlin", "CoreCommand.kt"), genKotlinCoreCommand(coreCmdSchema));
  writeFile(join(GENERATED_DIR, "kotlin", "CoreEvent.kt"), genKotlinCoreEvent(coreEvtSchema));
  writeFile(join(GENERATED_DIR, "kotlin", "HostRequest.kt"), genKotlinHostRequest(hostReqSchema));
  writeFile(join(GENERATED_DIR, "kotlin", "ProgressLocation.kt"), genKotlinProgressLocation(progressSchema));
  writeFile(join(GENERATED_DIR, "kotlin", "Content.kt"), genKotlinContent(contentSchema));
  writeFile(join(GENERATED_DIR, "kotlin", "SyncConflict.kt"), genKotlinSyncConflict(syncConflictSchema));

  // Kotlin - Phase 1 收尾
  writeFile(join(GENERATED_DIR, "kotlin", "StateRule.kt"), genKotlinStateRule(stateRuleSchema));

  // ArkTS - Phase 1
  writeFile(join(GENERATED_DIR, "arkts", "Route.ets"), genArkTsRoute(routeSchema));
  writeFile(join(GENERATED_DIR, "arkts", "UiEvent.ets"), genArkTsUiEvent(eventSchema));
  writeFile(join(GENERATED_DIR, "arkts", "UiState.ets"), genArkTsUiState(stateSchema));
  writeFile(join(GENERATED_DIR, "arkts", "ViewState.ets"), genArkTsViewState(viewSchema));
  writeFile(join(GENERATED_DIR, "arkts", "Motion.ets"), genArkTsMotion(motionSchema, motionFixtures));
  writeFile(join(GENERATED_DIR, "arkts", "Token.ets"), genArkTsToken(tokenSchema, tokenFixtures));

  // ArkTS - Phase 2
  writeFile(join(GENERATED_DIR, "arkts", "CoreCommand.ets"), genArkTsCoreCommand(coreCmdSchema));
  writeFile(join(GENERATED_DIR, "arkts", "CoreEvent.ets"), genArkTsCoreEvent(coreEvtSchema));
  writeFile(join(GENERATED_DIR, "arkts", "HostRequest.ets"), genArkTsHostRequest(hostReqSchema));
  writeFile(join(GENERATED_DIR, "arkts", "ProgressLocation.ets"), genArkTsProgressLocation(progressSchema));
  writeFile(join(GENERATED_DIR, "arkts", "Content.ets"), genArkTsContent(contentSchema));
  writeFile(join(GENERATED_DIR, "arkts", "SyncConflict.ets"), genArkTsSyncConflict(syncConflictSchema));

  // ArkTS - Phase 1 收尾
  writeFile(join(GENERATED_DIR, "arkts", "StateRule.ets"), genArkTsStateRule(stateRuleSchema));

  console.log("[codegen] generated swift / kotlin / arkts types (Phase 1 + Phase 2 + Phase 1 收尾)");
  console.log(`[codegen] Phase 1: route ids=${extractEnum(routeSchema, "id").length}, ui-event types=${extractEnum(eventSchema, "type").length}, motion ids=${extractEnum(motionSchema, "id").length}, token categories=${extractEnum(tokenSchema, "category").length}`);
  console.log(`[codegen] Registries: motion specs=${motionFixtures.length}, tokens=${tokenFixtures.length}`);
  console.log(`[codegen] Phase 2: core-command types=${extractEnum(coreCmdSchema, "type").length}, core-event types=${extractEnum(coreEvtSchema, "type").length}, host-request types=${extractEnum(hostReqSchema, "type").length}`);
  console.log(`[codegen] Phase 1 收尾: state-rule kinds=${extractEnum(stateRuleSchema, "kind").length}, severity=${extractEnum(stateRuleSchema, "severity").length}`);
}

generate();
