// Reader-UI Control Identity TypeScript contract
// Source of truth: contracts/control-identity.schema.json
// Generated by: A2 · Control Identity Foundation (2026-07-19)
//
// This file is hand-curated to match the JSON Schema; regenerating it from
// the schema requires the codegen pipeline (see tools/interaction-inventory/codegen-control-ids.mjs).

/**
 * Canonical control identity. The string form
 * `{domain}.{family}.{route}.{state}.{viewport}.{role}[.discriminator]`
 * is the stable join key across Figma / ScreenGraph / Web DOM / native runtimes.
 */
export interface ControlIdentity {
  /** Canonical control identity string. */
  controlId: string;
  /** Product domain; matches ScreenGraph runtimeFamily. */
  domain: ControlDomain;
  /** Component family derived from DOM tag + ARIA role + class hints. */
  family: ControlFamily;
  /** ScreenGraph routeId (kebab-case). */
  route: string;
  /** Variant pageState (kebab-case). */
  state: string;
  /** Target viewport. */
  viewport: ControlViewport;
  /** Semantic role atom. */
  role: ControlRole;
  /** Stable disambiguator within (domain, family, route, state, viewport, role). */
  discriminator: string;
  /** Source audit provenance. */
  source: ControlIdentitySource;
  /** Whether the candidate was auto-mapped or requires manual mapping. */
  mappingStatus: ControlMappingStatus;
  /** Optional human-readable mapping explanation. */
  mappingNotes: string | null;
  /** ScreenGraph component instance binding, if any. */
  screenGraphBinding: ScreenGraphBinding | null;
  /** Reserved Figma node id; always null in A2 baseline. */
  figmaNodeCandidate: string | null;
  /** Figma join status; always 'pending-figma-join' in A2 baseline. */
  figmaJoinStatus: "pending-figma-join" | "joined";
}

export type ControlDomain =
  | "discover"
  | "import"
  | "library"
  | "onboarding"
  | "reader"
  | "rss"
  | "settings"
  | "source"
  | "source-switch"
  | "sync"
  | "system"
  | "web-auth";

export type ControlFamily =
  | "button"
  | "icon-button"
  | "link"
  | "switch"
  | "checkbox"
  | "radio"
  | "slider"
  | "textbox"
  | "searchbox"
  | "combobox"
  | "option"
  | "tab"
  | "menuitem"
  | "menuitemcheckbox"
  | "menuitemradio"
  | "summary"
  | "listrow-action"
  | "treeitem"
  | "generic-button";

export type ControlViewport = "phone" | "compact" | "tablet" | "fold";

export type ControlRole =
  | "button"
  | "checkbox"
  | "combobox"
  | "link"
  | "menuitem"
  | "menuitemcheckbox"
  | "menuitemradio"
  | "option"
  | "radio"
  | "searchbox"
  | "slider"
  | "switch"
  | "tab"
  | "textbox"
  | "treeitem"
  | "summary";

export type ControlMappingStatus =
  | "auto-mapped"
  | "needs-manual-mapping"
  | "ambiguous-needs-review";

export interface ControlIdentitySource {
  candidateKey: string;
  selectorSha256: string;
  semanticStatus: "semantic-control" | "suspected-nonsemantic-control";
  domTag?: string;
  label?: string | null;
  uiEvent?: string | null;
  dataAttributes?: Record<string, string>;
}

export interface ScreenGraphBinding {
  componentInstanceId: string | null;
  componentType: string | null;
  bindingStatus: "bound" | "unresolved" | "pending-figma-join";
}

/**
 * Registry entry record as persisted to
 * `tools/interaction-inventory/generated/control-id-registry.json`.
 */
export interface ControlIdRegistryEntry extends ControlIdentity {
  /** ISO date when the entry was first materialized. */
  firstMaterializedAt: string;
  /** Schema version of the registry file. */
  schemaVersion: string;
}

export interface ControlIdRegistry {
  schemaVersion: string;
  generatedAt: string;
  generatedFrom: {
    inventoryPath: string;
    inventorySha256: string;
    screenGraphPath: string;
    screenGraphSha256: string;
    generatorPath: string;
  };
  totals: {
    candidates: number;
    semanticControls: number;
    suspectedNonSemanticControls: number;
    autoMapped: number;
    needsManualMapping: number;
    ambiguousNeedsReview: number;
    uniqueControlIds: number;
    pendingFigmaJoin: number;
  };
  entries: ControlIdRegistryEntry[];
}

/**
 * DOM identity mapping record. Describes how a `controlId` lands on the DOM
 * via the `data-control-id` attribute. Persisted to
 * `tools/interaction-inventory/generated/dom-identity-map.json`.
 */
export interface DomIdentityMapEntry {
  controlId: string;
  /** CSS attribute selector that uniquely resolves the control in the rendered DOM. */
  domSelector: string;
  /** Stable selector SHA-256, inherited from the IC0 audit. */
  selectorSha256: string;
  /** The `data-control-id` value to set on the matched element. */
  dataControlId: string;
  /** Route where this selector was first observed. */
  routeId: string;
  /** Viewport where this selector was first observed. */
  viewport: ControlViewport;
}

export interface DomIdentityMap {
  schemaVersion: string;
  generatedAt: string;
  entries: DomIdentityMapEntry[];
}
